// ── General bird pool ─────────────────────────────────────────────────────────
// Used for easy / medium modes. Mix of well-known, charismatic, and obscure.
const BIRDS = [

  // Africa
  { name: "Shoebill", fact: "Stands nearly 1.5 metres tall and stares at prey with both eyes forward like an owl — extremely unusual for a bird. It hunts lungfish by freezing motionless in swamps for hours, then striking with a bill that can decapitate its catch." },
  { name: "Secretary Bird", fact: "Kills snakes by stamping on them with feet that deliver a force five times its own body weight — fast enough that the snake cannot react. Despite being a raptor, it spends most of its life walking, covering up to 20 km a day on foot." },
  { name: "Hammerkop", fact: "Builds the largest nest of any bird relative to its size — a roofed fortress of sticks, mud and grass up to 1.5 metres across that can hold the weight of a grown adult. Pairs build up to five of these in a single year, often for no apparent reason." },
  { name: "Marabou Stork", fact: "Has a hollow leg bone connected to its lungs so it can use its legs as a radiator to cool blood in African heat. Its bald head and neck stay cleaner when plunged deep inside carcasses, and it can eat burning charcoal and old leather without apparent ill effect." },
  { name: "African Fish Eagle", fact: "The call of the African Fish Eagle is so iconic it is used as a generic 'Africa' sound effect in films set on other continents. It snatches fish from the surface with its talons while barely getting its feet wet, then flies off with a meal in under three seconds." },
  { name: "Lilac-breasted Roller", fact: "Gets its name from the spectacular rolling dive it performs during courtship — plummeting and twisting while calling loudly. It can see ultraviolet light, which reveals tracks and urine trails left by insects and lizards invisible to human eyes." },
  { name: "Southern Ground Hornbill", fact: "Lives in groups where only the dominant pair breeds, and helpers — including non-relatives — wait up to a decade for a chance to raise chicks. The group buries food caches and can remember locations for years. Individuals can live past 70." },
  { name: "Hoopoe", fact: "The female and chicks produce a foul-smelling liquid from their preen gland that coats the nest, deterring predators and bacteria. Despite the stench, it was considered sacred in ancient Egypt and appears in hieroglyphics. It also probes soil with its bill like a precision sewing machine." },
  { name: "Cape Sugarbird", fact: "Found only in South Africa's fynbos, it pollinates proteas so efficiently that the plants have evolved flowers matching the exact curve of its bill. The male's tail can be twice its body length and he carries it even while hovering in strong winds." },
  { name: "Ostrich", fact: "The largest living bird and the fastest running bird on Earth, reaching 70 km/h in a sprint. Its eye is bigger than its brain — each eyeball measures 5 cm across. Rather than burying its head in the sand, it lays its head flat on the ground to hide." },
  { name: "Saddle-billed Stork", fact: "One of Africa's tallest flying birds at up to 150 cm, with a bill so vivid — red, black and yellow with a yellow 'saddle' — that early explorers thought it must have been painted. Males and females are identical except for eye colour: males have brown eyes, females yellow." },
  { name: "African Skimmer", fact: "Flies low over rivers with its lower mandible slicing through the water like a plow blade. The moment it feels a fish, the upper bill snaps shut in a split second. Its lower mandible grows faster than the upper to compensate for constant wear from dragging through water." },
  { name: "Pel's Fishing Owl", fact: "One of the world's largest owls, specialising entirely in fish. Unlike other owls it has no sound-dampening feathers — waterproofing matters more than silence when hunting fish — and its feet have spiny scales for gripping slippery prey. Its call is a deep booming moan heard a kilometre away." },
  { name: "Hartlaub's Turaco", fact: "The only birds to have true red and green pigments in their feathers — most birds fake these colours with structure. Turacos make their own copper-based pigments called turacin (red) and turacoverdin (green) that dissolve slightly in water, giving the illusion of bleeding colour in heavy rain." },
  { name: "Superb Starling", fact: "A common East African bird so brilliantly coloured — metallic blue-green above, chestnut below, with a white chest band — that tourists often mistake it for an exotic rarity. Despite its looks it's a bold opportunist that will steal food from café tables." },
  { name: "Kori Bustard", fact: "Possibly the heaviest flying bird on Earth, with males reaching 19 kg. During courtship the male inflates its neck to balloon size and fans its white undertail feathers until it looks twice its normal size. It eats toxic plants and venomous snakes without apparent harm." },
  { name: "Grey Crowned Crane", fact: "The only crane that roosts in trees — its hind toe is long enough to grip branches. It stamps its feet while foraging to flush insects, and its golden crown of bristled feathers vibrates in response to sound, possibly acting as a resonator for its booming call." },
  { name: "Rosy-faced Lovebird", fact: "In cold desert nights pairs tuck their heads under each other's wings and sleep pressed together, regulating each other's body temperature. Females carry nesting material tucked into their rump feathers rather than in their bills — a method unique among parrots." },
  { name: "Black-and-white Casqued Hornbill", fact: "A large rainforest hornbill of Central Africa that relies on figs and uses its casque — a hollow ridge on the bill — to amplify its resonant calls through the forest. Pairs remain bonded for life and the male seals the female into the nest cavity with mud and droppings." },
  { name: "African Pitta", fact: "A jewel of the rainforest floor — glossy blue, green, red and black — yet so secretive that it was once considered rare. It is now known to be a common migrant that simply hides perfectly in leaf litter. It hammers snails against anvil stones to break the shells." },
  { name: "Martial Eagle", fact: "Africa's largest eagle, powerful enough to knock a grown person off their feet. It can spot prey from 5 km away and has been documented killing small antelopes, monitor lizards and young baboons. Its population has crashed due to persecution and habitat loss." },
  { name: "Bateleur", fact: "Spends up to eight hours a day airborne, covering 300–400 km while barely flapping. Its name is French for 'street performer' — a reference to its rocking, acrobatic flight. The bare red face skin flushes darker when the bird is agitated or excited." },
  { name: "Namaqua Sandgrouse", fact: "Males fly up to 80 km to a waterhole, wade in, and soak their specially adapted belly feathers — which can hold 15–20 ml of water like a sponge. They fly back and the chicks drink directly from the feathers. Chicks can do this from day one." },
  { name: "Long-crested Eagle", fact: "Its extraordinarily long floppy head plumes — up to 15 cm — give it a permanently surprised expression and bounce comically as it flies. Despite looking dramatic it is a specialist rodent hunter, eating almost nothing but voles and other small mammals." },
  { name: "Pennant-winged Nightjar", fact: "The breeding male grows two inner wing feathers that extend up to 50 cm beyond the wingtip as white trailing streamers. He flies with these huge pennants fluttering behind him at dusk to attract females. After breeding season he moults them off and looks like a completely different bird." },
  { name: "Black Heron", fact: "Hunts by spreading both wings into a perfect black umbrella over the water, creating a patch of shade. Fish swim into it seeking shelter from the sun, and the heron picks them off. It is the only animal known to create a tool entirely from its own body to lure prey." },
  { name: "Greater Honeyguide", fact: "The only bird known to actively guide humans to food. Using a distinctive chattering call and fluttering flight, it leads honey-hunters to bees' nests — sometimes over a kilometre — then waits for them to break the hive open before eating the wax and larvae left behind. The partnership is ancient enough to have its own traditional signals in Mozambique." },
  { name: "Long-tailed Widowbird", fact: "The male's tail feathers reach 50 cm — four times its body length — and he hauls them through the air in a slow, laboured display flight above the savannah. Scientists who glued on artificial extensions found those males attracted dramatically more females, confirming the tail is pure sexual advertising at an honest cost." },
  { name: "African Broadbill", fact: "Performs one of the strangest courtship displays in Africa: the male flies in tight circles around a branch so fast his wings create a mechanical purring sound, then suddenly freezes and puffs himself into a round blob to show off his vivid purple throat patch." },
  { name: "African Finfoot", fact: "An extremely shy waterbird that swims low in the water like a grebe but climbs into waterside vegetation to escape. The female carries newly hatched chicks in special pouches of skin under her wings while swimming — discovered by accident when a bird was spooked and chicks tumbled out." },
  { name: "Sunbird Asity", fact: "A Madagascan oddity distantly related to broadbills but looking exactly like a sunbird — a striking example of convergent evolution. The male has a vivid wattle of electric blue and green bare skin around the eye that inflates during breeding season and deflates completely afterwards." },
  { name: "Lappet-faced Vulture", fact: "The most dominant vulture at a carcass in Africa — other species wait for it to open the hide before they can feed. The bare red folds of skin on its face help it look intimidating. It eats skin, tendons and bone fragments that other scavengers cannot process." },
  { name: "Hooded Vulture", fact: "One of the smallest African vultures, with a thin bill perfectly sized for probing into crevices and eye sockets that larger vultures can't reach. It has recently learned to follow fishing trawlers and scavenge at rubbish dumps, but is still one of the fastest-declining birds in Africa." },
  { name: "Verreaux's Eagle", fact: "One of the most specialised predators on Earth — up to 98% of its diet is rock hyrax, a rabbit-sized mammal. So dependent on hyrax colonies that when they disappear from an area the eagles abandon their territory rather than switch prey. Pairs use the same cliff nest for decades, adding sticks each year until it is enormous." },
  { name: "Taita Falcon", fact: "A tiny torpedo-shaped falcon that nests exclusively on sheer cliff faces, including inside Batoka Gorge at Victoria Falls. Fewer than 200 are thought to exist globally, yet it is so fast and agile it regularly catches swifts — themselves masters of aerial speed." },
  { name: "White-fronted Bee-eater", fact: "Lives in extended family groups where non-breeding helpers assist the dominant pair — but also 'kidnaps' young from other pairs within the colony, harassing them until a fledgling abandons its own parents and follows its abductors, boosting the kidnapper's own reproductive success." },
  { name: "African Jacana", fact: "Walks on floating lily pads on extraordinarily long toes that spread its weight like snowshoes. Sex roles are reversed: females are larger, hold territories and mate with several males. Each male incubates eggs and rears chicks alone — tucking the tiny chicks under his wings and wading to safety with their legs dangling out." },
  { name: "Knysna Turaco", fact: "A brilliantly coloured forest turaco of South Africa's Garden Route whose emerald green plumage comes from turacoverdin, a copper-based pigment found in no other animal on Earth. It runs along branches with surprising speed and agility rather than flying between them." },
  { name: "African Openbill", fact: "Its bill has a permanent gap when closed — not a deformity but a precision tool. The edges of the mandibles meet only at the tip, forming curved forceps perfectly shaped for gripping and twisting open apple snail shells and freshwater mussels without crushing them." },
  { name: "Palm-nut Vulture", fact: "The only vulture that eats primarily plant material — it feeds mainly on the husks of oil palm and raphia palm fruits. This vegetarian diet allows it to thrive in dense forest where other vultures rarely venture. Despite being a vulture it also readily eats fish, frogs and crabs." },

  // Asia
  { name: "Indian Peafowl", fact: "The male's train isn't his tail — it's elongated back plumage. Each feather has an iridescent 'eye' made not from pigment but from nanostructures that reflect light differently at every angle. The train rattles and shimmers during display and produces infrasound below human hearing that females may sense through their feet." },
  { name: "Himalayan Monal", fact: "The national bird of Nepal, the male is arguably the most colourful bird in Asia — covered in metallic green, purple, copper and blue, with no two patches the same hue. It digs through deep snow with its heavy curved bill to reach roots and tubers at altitudes above 4,000 metres." },
  { name: "Red-crowned Crane", fact: "One of the rarest cranes on Earth, with fewer than 3,000 remaining. In Japanese culture it symbolises longevity and fidelity, appearing on the 1,000-yen note. Pairs bond for life and perform elaborate synchronised dances — leaping and calling in perfect unison — that strengthen the bond year after year." },
  { name: "Oriental Pied Hornbill", fact: "Like all hornbills, the male seals the female inside a tree hollow with mud and droppings, leaving only a slit through which he passes food for months. The female uses the enforced isolation to safely moult all her flight feathers at once — something she couldn't do while exposed to predators." },
  { name: "Sarus Crane", fact: "The world's tallest flying bird, standing up to 180 cm. Sacred in India and depicted in ancient Sanskrit literature as a symbol of faithful love, because pairs reputedly grieve when a partner dies. Farmers deliberately protect nesting Sarus cranes in rice paddies, believing harming one brings misfortune." },
  { name: "Indian Roller", fact: "The state bird of three Indian states, famous for its dazzling aerial display in which it rolls and tumbles to reveal brilliant turquoise underwings — colour invisible when the bird is perched. Farmers welcome it because it follows tractors to snatch exposed insects and earthworms." },
  { name: "Painted Stork", fact: "Feeds by wading with its partly open bill submerged and sweeping it side to side, snapping shut purely by touch the instant a fish brushes it. The faint pink flush on its wing tips deepens during breeding season — the only stork to change colour seasonally." },
  { name: "Indian Paradise Flycatcher", fact: "The male comes in two forms — white or chestnut — and grows two central tail feathers that stream up to 30 cm behind him. He fans and waves them during courtship while the female sits apparently unmoved, assessing how long he can maintain the performance." },
  { name: "Siberian Crane", fact: "Makes one of the longest migrations of any bird — breeding in remote Arctic Russia and wintering almost entirely at China's Poyang Lake. With fewer than 4,000 left, its survival hinges on a single wetland. It uses touch rather than sight to probe underwater for the plant roots it eats." },
  { name: "Great Hornbill", fact: "The hollow casque on the bill acts as a resonator for its deep booming call, which carries far through the dense forest. The male feeds the sealed-in female up to 150 times a day, passing food piece by piece through the narrow slit. Pairs stay together for life and can live over 50 years." },
  { name: "Brahminy Kite", fact: "Considered sacred in Bali, where it is the divine vehicle of Vishnu, and revered across Hindu and Buddhist cultures throughout Southeast Asia. It scavenges shorelines and rubbish dumps with equal comfort, but also hunts live prey — snatching fish, frogs and even bats with a sudden plunging strike." },
  { name: "Sri Lanka Frogmouth", fact: "One of the world's most perfectly camouflaged birds. By day it sits motionless on a mossy branch with its eyes slitted and bill raised, looking precisely like a broken stub of bark. It is endemic to Sri Lanka and the Western Ghats and was unknown to science until 1849." },
  { name: "Stork-billed Kingfisher", fact: "One of the largest kingfishers in Asia, with a bill so disproportionately huge — red, massive and cartoon-like — that it seems physically improbable. It dives into rivers to catch large fish but also eats lizards, frogs and small birds, waiting motionless on a branch before plunging." },
  { name: "Blue Pitta", fact: "A jewel of the forest floor — electric blue, orange and black — that is heard far more often than seen. It hops through leaf litter turning over dead leaves with its bill in search of earthworms. Males sing persistently at dawn from a favourite perch, but disappear into undergrowth almost instantly." },
  { name: "Jerdon's Courser", fact: "A nocturnal wader so rarely seen that it was believed extinct for over 80 years before being rediscovered in 1986 in a steep rocky gorge in India. It forages only at night on boulder-strewn streamsides and retreats to rocky crevices by day, making it almost impossible to survey." },
  { name: "Malabar Trogon", fact: "The male is crimson below and iridescent dark blue-green above, but sits so still in the forest shade that it vanishes despite its colours. Endemic to the Western Ghats and Sri Lanka, it nests in tree cavities it excavates itself, using its serrated bill like a saw." },
  { name: "Spoon-billed Sandpiper", fact: "Its spatula-shaped bill is unique among waders and acts like a sensitive metal detector, sweeping through soft mud and snapping shut on tiny invertebrates. Critically endangered, with perhaps only 500 remaining, it migrates from Arctic Russia to Bangladesh and Myanmar along a flyway that has lost most of its stopover wetlands." },
  { name: "Milky Stork", fact: "A coastal stork of mangroves and tidal mudflats in Southeast Asia that feeds with its bill partly open, feeling for fish and crabs by touch. Its population has plummeted as mangroves are cleared for aquaculture, and it now survives mainly in a handful of protected sites in Sumatra." },
  { name: "Bar-headed Goose", fact: "Regularly flies directly over the Himalayas at altitudes above 7,000 metres — sometimes passing over Everest. Its haemoglobin binds oxygen far more efficiently than that of lowland birds, and its heart rate during this extreme exertion is higher than any other bird ever measured." },
  { name: "Mandarin Duck", fact: "The male's courtship plumage includes a pair of orange 'sail' feathers that project upright from the wing — used purely for display and moulted immediately after the breeding season. Considered a symbol of marital fidelity in China and Japan, though pairs actually separate each year and choose new mates." },
  { name: "Walden's Hornbill", fact: "Critically endangered and confined to a handful of Philippine islands, it was named for an English ornithologist and is so rarely photographed that basic facts about its behaviour remain unknown. Its casque and bill are brighter yellow-orange in males, and pairs engage in noisy aerial chases through the forest canopy." },
  { name: "Bornean Bristlehead", fact: "Possibly the strangest bird in Borneo — a chunky black-and-red forest bird whose bare red head is studded with small fleshy knobs, giving it a warty, alien appearance. It has no close living relatives; its whole family contains just this one species. It travels in noisy flocks and the knobs' function remains unknown." },
  { name: "Wrinkled Hornbill", fact: "Has a deeply corrugated bill and casque that makes it look like it has been badly crumpled. Found only in the lowland rainforests of Borneo and the Malay Peninsula, it is heavily dependent on old-growth trees with cavities large enough to seal a female inside for incubation." },
  { name: "Gurney's Pitta", fact: "Once thought extinct, rediscovered in Thailand in 1986 and again in Myanmar in 2003. The male is a mosaic of deep blue, yellow and black. It lives in lowland rainforest that has been almost entirely logged, and surveys suggest only a few hundred individuals remain." },
  { name: "Philippine Eagle", fact: "One of the world's largest eagles, with a wingspan up to 220 cm and eyes described by researchers as 'almost human' in expressiveness. It hunts flying lemurs through dense canopy at speed. Critically endangered, with under 800 left, and the national symbol of the Philippines." },
  { name: "Palawan Peacock-Pheasant", fact: "The male carries an iridescent blue-green fan of tail feathers covered in metallic 'eyes', which he fans open and rocks from side to side during courtship while the female circles to examine each eye from every angle. Found only on the Philippine island of Palawan." },
  { name: "Storm's Stork", fact: "One of the world's rarest storks, with probably fewer than 500 remaining. Confined to undisturbed lowland rivers in Borneo, Sumatra and Malaysia, it nests in huge trees overhanging the water. Almost nothing is known about its breeding behaviour because it is so rarely observed." },
  { name: "Crested Serpent Eagle", fact: "Specialises almost entirely in snakes and lizards, using its broad rounded wings to slow-glide over the forest canopy while watching for prey below. When it spots a snake it drops and pins it with powerful feet before biting the back of the skull — immune to most snake venoms it encounters." },
  { name: "Cheer Pheasant", fact: "A long-tailed pheasant of steep Himalayan hillsides whose male has 18 tail feathers — more than any other pheasant. Its name comes from its call, a loud ringing 'chir-chir-chirwa', not its demeanour. It is so good at hiding in rocky scrub that locals describe it as 'impossible to find twice.'" },
  { name: "Satyr Tragopan", fact: "The male has a brilliant crimson breast studded with white spots like a polka-dot spotlight. During courtship he inflates two blue horns on his head and a bib of brilliant blue and red skin that expands to the size of a handkerchief — then suddenly flashes it at the female from behind a rock." },
  { name: "Temminck's Tragopan", fact: "Found high in the Eastern Himalayas, the male performs one of the most spectacular displays in the bird world: crouching low, spreading his spotted wings as a backdrop, and inflating an extraordinary patterned bib of blue, red and white skin that hangs down from his throat like a painted flag." },
  { name: "Green Peafowl", fact: "Larger and arguably more elegant than the Indian Peafowl, with iridescent green and bronze plumage and a neat, upright crest. Unlike its cousin, both sexes carry long train feathers. Once widespread across Southeast Asia, it has been hunted and its wetland habitat drained until only scattered populations remain." },
  { name: "Wilson's Bird-of-Paradise", fact: "Has a bare turquoise-blue crown — one of the only birds with genuinely blue skin rather than blue feathers. The male painstakingly clears the forest floor of every leaf before performing his display, creating a stage. The curling green tail wires are held in a tight spiral at rest and flung outward during display." },
  { name: "Wallace's Standardwing", fact: "Named for Alfred Russel Wallace, who discovered it on the island of Bacan in 1858 and wrote that it was 'more like a work of art than a natural production.' The male carries two long white breast plumes — the 'standards' — that he erects and vibrates while hanging upside down in a communal display tree." },
  { name: "Maleo", fact: "Lays eggs six times the size of a chicken egg in geothermal or sun-warmed sand, then abandons them. The chick digs out alone, tunnelling upward through half a metre of sand over several days, and emerges fully feathered and able to fly within hours — having received no parental care whatsoever." },
  { name: "Nicobar Pigeon", fact: "" },
  { name: "Black-naped Pheasant-Pigeon", fact: "" },
  { name: "Halmahera Paradise Crow", fact: "" },
  { name: "Spot-billed Pelican", fact: "" },
  { name: "Pied Kingfisher", fact: "" },

  // Australasia & New Zealand
  { name: "Cassowary", fact: "" },
  { name: "Kea", fact: "" },
  { name: "Kiwi", fact: "" },
  { name: "Tawny Frogmouth", fact: "" },
  { name: "Superb Lyrebird", fact: "" },
  { name: "Rifleman", fact: "" },
  { name: "Laughing Kookaburra", fact: "" },
  { name: "Kakapo", fact: "" },
  { name: "Satin Bowerbird", fact: "" },
  { name: "Regent Bowerbird", fact: "" },
  { name: "Tooth-billed Bowerbird", fact: "" },
  { name: "Vogelkop Bowerbird", fact: "" },
  { name: "Raggiana Bird-of-Paradise", fact: "" },
  { name: "King Bird-of-Paradise", fact: "" },
  { name: "Western Parotia", fact: "" },
  { name: "King-of-Saxony Bird-of-Paradise", fact: "" },
  { name: "Blue Bird-of-Paradise", fact: "" },
  { name: "Twelve-wired Bird-of-Paradise", fact: "" },
  { name: "Magnificent Riflebird", fact: "" },
  { name: "Victoria Crowned Pigeon", fact: "" },
  { name: "Palm Cockatoo", fact: "" },
  { name: "Gang-gang Cockatoo", fact: "" },
  { name: "Glossy Black-Cockatoo", fact: "" },
  { name: "Yellow-tailed Black-Cockatoo", fact: "" },
  { name: "Swift Parrot", fact: "" },
  { name: "Orange-bellied Parrot", fact: "" },
  { name: "Pesquet's Parrot", fact: "" },
  { name: "Eclectus Parrot", fact: "" },
  { name: "Emu", fact: "" },
  { name: "Wedge-tailed Eagle", fact: "" },
  { name: "Australian Brushturkey", fact: "" },
  { name: "Malleefowl", fact: "" },
  { name: "Plains-wanderer", fact: "" },
  { name: "Night Parrot", fact: "" },
  { name: "Gouldian Finch", fact: "" },
  { name: "Splendid Fairywren", fact: "" },
  { name: "Noisy Scrubbird", fact: "" },
  { name: "Powerful Owl", fact: "" },
  { name: "Apostlebird", fact: "" },
  { name: "Chowchilla", fact: "" },
  { name: "Takahe", fact: "" },
  { name: "Wrybill", fact: "" },
  { name: "Black Stilt", fact: "" },
  { name: "New Zealand Bellbird", fact: "" },
  { name: "Hihi", fact: "" },
  { name: "Kokako", fact: "" },
  { name: "Saddleback", fact: "" },
  { name: "Kaka", fact: "" },
  { name: "Weka", fact: "" },
  { name: "New Zealand Dotterel", fact: "" },
  { name: "Logrunner", fact: "" },

  // Europe
  { name: "Bearded Vulture", fact: "" },
  { name: "European Bee-eater", fact: "" },
  { name: "Common Kingfisher", fact: "" },
  { name: "Atlantic Puffin", fact: "" },
  { name: "Great Bustard", fact: "" },
  { name: "White-tailed Eagle", fact: "" },
  { name: "Eurasian Bittern", fact: "" },
  { name: "Dalmatian Pelican", fact: "" },
  { name: "Eurasian Eagle Owl", fact: "" },
  { name: "Great Grey Shrike", fact: "" },
  { name: "Wallcreeper", fact: "" },
  { name: "Snow Bunting", fact: "" },
  { name: "Eurasian Dotterel", fact: "" },
  { name: "Ruff", fact: "" },
  { name: "Red Kite", fact: "" },
  { name: "Eurasian Roller", fact: "" },
  { name: "Wryneck", fact: "" },
  { name: "Eurasian Spoonbill", fact: "" },
  { name: "Black Woodpecker", fact: "" },
  { name: "Hawfinch", fact: "" },
  { name: "Penduline Tit", fact: "" },
  { name: "White-winged Snowfinch", fact: "" },
  { name: "Cinereous Vulture", fact: "" },
  { name: "Common Firecrest", fact: "" },
  { name: "Bluethroat", fact: "" },
  { name: "Pygmy Cormorant", fact: "" },
  { name: "Eurasian Scops Owl", fact: "" },
  { name: "Tengmalm's Owl", fact: "" },
  { name: "Great Snipe", fact: "" },
  { name: "Eurasian Woodcock", fact: "" },

  // North America
  { name: "Arctic Tern", fact: "" },
  { name: "Peregrine Falcon", fact: "" },
  { name: "Snowy Owl", fact: "" },
  { name: "Greater Roadrunner", fact: "" },
  { name: "Clark's Nutcracker", fact: "" },
  { name: "Burrowing Owl", fact: "" },
  { name: "Common Loon", fact: "" },
  { name: "Osprey", fact: "" },
  { name: "Anna's Hummingbird", fact: "" },
  { name: "Bobolink", fact: "" },
  { name: "Red Knot", fact: "" },
  { name: "Limpkin", fact: "" },
  { name: "Snail Kite", fact: "" },
  { name: "American Dipper", fact: "" },
  { name: "Harlequin Duck", fact: "" },
  { name: "Painted Bunting", fact: "" },
  { name: "Scissor-tailed Flycatcher", fact: "" },
  { name: "Long-billed Curlew", fact: "" },
  { name: "Whooping Crane", fact: "" },
  { name: "California Condor", fact: "" },
  { name: "Vermilion Flycatcher", fact: "" },
  { name: "Phainopepla", fact: "" },
  { name: "Elf Owl", fact: "" },
  { name: "Elegant Trogon", fact: "" },
  { name: "Thick-billed Parrot", fact: "" },
  { name: "Marbled Murrelet", fact: "" },
  { name: "Western Grebe", fact: "" },
  { name: "Spruce Grouse", fact: "" },
  { name: "Tufted Puffin", fact: "" },
  { name: "Rhinoceros Auklet", fact: "" },
  { name: "Ivory Gull", fact: "" },
  { name: "Ross's Gull", fact: "" },
  { name: "Steller's Sea Eagle", fact: "" },
  { name: "Bristle-thighed Curlew", fact: "" },
  { name: "Kirtland's Warbler", fact: "" },
  { name: "Prothonotary Warbler", fact: "" },
  { name: "Gunnison Sage-Grouse", fact: "" },
  { name: "Roseate Spoonbill", fact: "" },

  // Central America & Caribbean
  { name: "Resplendent Quetzal", fact: "" },
  { name: "Turquoise-browed Motmot", fact: "" },
  { name: "Keel-billed Toucan", fact: "" },
  { name: "Harpy Eagle", fact: "" },
  { name: "Sunbittern", fact: "" },
  { name: "Bee Hummingbird", fact: "" },
  { name: "Wire-tailed Manakin", fact: "" },
  { name: "Club-winged Manakin", fact: "" },
  { name: "Amazonian Umbrellabird", fact: "" },
  { name: "Spectacled Owl", fact: "" },
  { name: "Sungrebe", fact: "" },
  { name: "Agami Heron", fact: "" },
  { name: "Zigzag Heron", fact: "" },
  { name: "Snowcap", fact: "" },
  { name: "Royal Flycatcher", fact: "" },
  { name: "Purple-crowned Fairy", fact: "" },
  { name: "Fiery-throated Hummingbird", fact: "" },
  { name: "Great Curassow", fact: "" },
  { name: "Lovely Cotinga", fact: "" },
  { name: "Snowy Cotinga", fact: "" },

  // South America
  { name: "Andean Condor", fact: "" },
  { name: "Hoatzin", fact: "" },
  { name: "Cock-of-the-rock", fact: "" },
  { name: "Horned Screamer", fact: "" },
  { name: "Jabiru", fact: "" },
  { name: "Inca Tern", fact: "" },
  { name: "Emperor Penguin", fact: "" },
  { name: "Rockhopper Penguin", fact: "" },
  { name: "Macaroni Penguin", fact: "" },
  { name: "Magellanic Penguin", fact: "" },
  { name: "Torrent Duck", fact: "" },
  { name: "Oilbird", fact: "" },
  { name: "Capuchinbird", fact: "" },
  { name: "Purple-breasted Cotinga", fact: "" },
  { name: "Banded Cotinga", fact: "" },
  { name: "Long-wattled Umbrellabird", fact: "" },
  { name: "Common Potoo", fact: "" },
  { name: "Great Potoo", fact: "" },
  { name: "Pale-winged Trumpeter", fact: "" },
  { name: "Giant Antpitta", fact: "" },
  { name: "Coppery-chested Jacamar", fact: "" },
  { name: "Rufescent Tiger Heron", fact: "" },
  { name: "Titicaca Grebe", fact: "" },
  { name: "James's Flamingo", fact: "" },
  { name: "Puna Flamingo", fact: "" },
  { name: "Hooded Grebe", fact: "" },
  { name: "Giant Coot", fact: "" },
  { name: "Wattled Curassow", fact: "" },
  { name: "Maguari Stork", fact: "" },
  { name: "Toco Toucan", fact: "" },

  // Seabirds & Polar
  { name: "Wandering Albatross", fact: "" },
  { name: "Waved Albatross", fact: "" },
  { name: "Light-mantled Albatross", fact: "" },
  { name: "Southern Giant Petrel", fact: "" },
  { name: "Snow Petrel", fact: "" },
  { name: "Blue-footed Booby", fact: "" },
  { name: "Red-footed Booby", fact: "" },
  { name: "Magnificent Frigatebird", fact: "" },
  { name: "White Tern", fact: "" },
  { name: "South Polar Skua", fact: "" },
  { name: "Long-tailed Jaeger", fact: "" },
  { name: "Swallow-tailed Gull", fact: "" },
  { name: "Sooty Shearwater", fact: "" },
  { name: "Manx Shearwater", fact: "" },
  { name: "Wilson's Storm Petrel", fact: "" },
  { name: "Red-billed Tropicbird", fact: "" },
  { name: "White-tailed Tropicbird", fact: "" },
  { name: "Abbott's Booby", fact: "" },
  { name: "Masked Booby", fact: "" },
  { name: "Brown Noddy", fact: "" },
  { name: "Christmas Frigatebird", fact: "" },

  // Owls & Nightbirds
  { name: "Great Grey Owl", fact: "" },
  { name: "Blakiston's Fish Owl", fact: "" },
  { name: "Verreaux's Eagle Owl", fact: "" },
  { name: "Crested Owl", fact: "" },
  { name: "Long-eared Owl", fact: "" },
  { name: "Barn Owl", fact: "" },
  { name: "Papuan Frogmouth", fact: "" },
  { name: "Standard-winged Nightjar", fact: "" },
  { name: "Lyre-tailed Nightjar", fact: "" },
  { name: "Pharaoh Eagle Owl", fact: "" },

];

// ── Hard-mode bird pool ───────────────────────────────────────────────────────
// Compound hyphenated names that match the SNEAKY fake-name generator style.
const HARD_BIRDS = [
  { name: "Yellow-rumped Warbler", fact: "" },
  { name: "Black-crowned Night Heron", fact: "" },
  { name: "Red-tailed Hawk", fact: "" },
  { name: "White-throated Sparrow", fact: "" },
  { name: "Blue-winged Teal", fact: "" },
  { name: "Golden-fronted Woodpecker", fact: "" },
  { name: "Red-breasted Nuthatch", fact: "" },
  { name: "Yellow-bellied Sapsucker", fact: "" },
  { name: "Golden-crowned Kinglet", fact: "" },
  { name: "Black-bellied Plover", fact: "" },
  { name: "White-crowned Sparrow", fact: "" },
  { name: "Chestnut-backed Chickadee", fact: "" },
  { name: "Rufous-tailed Hummingbird", fact: "" },
  { name: "Black-backed Woodpecker", fact: "" },
  { name: "Olive-backed Sunbird", fact: "" },
  { name: "White-bellied Sea Eagle", fact: "" },
  { name: "Rufous-crowned Sparrow", fact: "" },
  { name: "Yellow-billed Oxpecker", fact: "" },
  { name: "Blue-naped Mousebird", fact: "" },
  { name: "Chestnut-sided Warbler", fact: "" },
  { name: "Red-faced Cormorant", fact: "" },
  { name: "White-winged Crossbill", fact: "" },
  { name: "Black-headed Grosbeak", fact: "" },
  { name: "Yellow-fronted Canary", fact: "" },
  { name: "Rufous-bellied Niltava", fact: "" },
  { name: "Purple-backed Thornbill", fact: "" },
  { name: "Blue-faced Honeyeater", fact: "" },
  { name: "Red-necked Phalarope", fact: "" },
  { name: "White-cheeked Pintail", fact: "" },
  { name: "Tawny-flanked Prinia", fact: "" },
  { name: "Golden-backed Weaver", fact: "" },
  { name: "Black-winged Stilt", fact: "" },
  { name: "Buff-fronted Owl", fact: "" },
  { name: "Yellow-throated Longclaw", fact: "" },
  { name: "White-headed Vulture", fact: "" },
  { name: "Red-chested Swallow", fact: "" },
  { name: "Blue-spotted Wood Dove", fact: "" },
  { name: "Pale-billed Woodpecker", fact: "" },
  { name: "Black-throated Mango", fact: "" },
  { name: "White-tipped Dove", fact: "" },
  { name: "Golden-olive Woodpecker", fact: "" },
  { name: "Purple-crowned Fairywren", fact: "" },
  { name: "Chestnut-eared Finch", fact: "" },
  { name: "Red-capped Robin", fact: "" },
  { name: "Blue-cheeked Bee-eater", fact: "" },
  { name: "White-browed Coucal", fact: "" },
  { name: "Yellow-crowned Night Heron", fact: "" },
  { name: "Buff-spotted Flufftail", fact: "" },
  { name: "Grey-headed Albatross", fact: "" },
  { name: "Brown-hooded Kingfisher", fact: "" },
  { name: "White-backed Night Heron", fact: "" },
  { name: "Black-chested Snake Eagle", fact: "" },
  { name: "Rufous-naped Lark", fact: "" },
  { name: "White-eared Barbet", fact: "" },
  { name: "Golden-headed Cisticola", fact: "" },
  { name: "Red-fronted Parrot", fact: "" },
  { name: "Black-faced Antbird", fact: "" },
  { name: "Blue-billed Malimbe", fact: "" },
  { name: "Chestnut-capped Blackbird", fact: "" },
  { name: "Yellow-whiskered Greenbul", fact: "" },
  { name: "White-backed Mousebird", fact: "" },
  { name: "Grey-backed Fiscal", fact: "" },
  { name: "Brown-backed Woodpecker", fact: "" },
  { name: "Blue-crowned Hanging Parrot", fact: "" },
  { name: "Pale-headed Rosella", fact: "" },
  { name: "Red-legged Thrush", fact: "" },
  { name: "Chestnut-flanked White-eye", fact: "" },
  { name: "Golden-cheeked Warbler", fact: "" },
  { name: "Blue-throated Macaw", fact: "" },
  { name: "White-necked Puffbird", fact: "" },
  { name: "Purple-rumped Sunbird", fact: "" },
  { name: "White-bearded Manakin", fact: "" },
  { name: "Crimson-backed Flameback", fact: "" },
  { name: "Blue-backed Tanager", fact: "" },
  { name: "Black-and-yellow Broadbill", fact: "" },
  { name: "Rusty-faced Parrot", fact: "" },
  { name: "White-tailed Nuthatch", fact: "" },
  { name: "Chestnut-headed Bee-eater", fact: "" },
  { name: "Yellow-billed Stork", fact: "" },
  { name: "Red-headed Weaver", fact: "" },
  { name: "Blue-mantled Thornbill", fact: "" },
  { name: "Grey-capped Warbler", fact: "" },
  { name: "Buff-banded Rail", fact: "" },
  { name: "White-rumped Shama", fact: "" },
  { name: "Rufous-backed Robin", fact: "" },
  { name: "Golden-winged Warbler", fact: "" },
  { name: "Purple-naped Lory", fact: "" },
  { name: "Black-capped Donacobius", fact: "" },
  { name: "Orange-backed Woodpecker", fact: "" },
  { name: "White-crested Hornbill", fact: "" },
  { name: "Blue-headed Racket-tail", fact: "" },
  { name: "Red-billed Firefinch", fact: "" },
  { name: "Yellow-eared Bulbul", fact: "" },
  { name: "Grey-necked Wood Rail", fact: "" },
  { name: "Tawny-browed Owl", fact: "" },
  { name: "Chestnut-breasted Wheatear", fact: "" },
  { name: "White-lored Oriole", fact: "" },
  { name: "Brown-winged Starling", fact: "" },
  { name: "Rufous-sided Crake", fact: "" },
  { name: "Golden-tailed Parrotlet", fact: "" },
  { name: "Grey-hooded Attila", fact: "" },
  { name: "Dusky-billed Parrotlet", fact: "" },
  { name: "Black-banded Crake", fact: "" },
  { name: "Tawny-chested Flycatcher", fact: "" },
  { name: "Cinnamon-rumped Foliage-gleaner", fact: "" },
  { name: "White-shouldered Fire-eye", fact: "" },
  { name: "Dusky-throated Antshrike", fact: "" },
  { name: "Brown-chested Jungle Flycatcher", fact: "" },
  { name: "Rufous-throated Bronze Cuckoo", fact: "" },
  { name: "Tawny-winged Woodcreeper", fact: "" },
  { name: "White-browed Tit-warbler", fact: "" },
  { name: "Rufous-capped Nunlet", fact: "" },
  { name: "Black-tipped Cotinga", fact: "" },
  { name: "Yellow-green Vireo", fact: "" },
  { name: "Chestnut-crowned Antpitta", fact: "" },
  { name: "White-ringed Flycatcher", fact: "" },
  { name: "Buff-rumped Warbler", fact: "" },
  { name: "Red-masked Parakeet", fact: "" },
  { name: "Blue-and-yellow Tanager", fact: "" },
  { name: "Grey-mantled Wren", fact: "" },
  { name: "Orange-crowned Euphonia", fact: "" },
  { name: "Black-eared Cuckoo", fact: "" },
  { name: "Rufous-bellied Seedsnipe", fact: "" },
  { name: "White-chinned Petrel", fact: "" },
  { name: "Chestnut-collared Longspur", fact: "" },
  { name: "Yellow-crowned Amazon", fact: "" },
  { name: "Brown-capped Vireo", fact: "" },
  { name: "Tawny-crowned Pygmy Tyrant", fact: "" },
  { name: "Pale-vented Pigeon", fact: "" },
  { name: "Red-throated Pipit", fact: "" },
  { name: "Grey-and-buff Woodpecker", fact: "" },
  { name: "White-naped Tit", fact: "" },
  { name: "Rufous-winged Sparrow", fact: "" },
  { name: "Black-browed Albatross", fact: "" },
  { name: "Golden-breasted Starling", fact: "" },
  { name: "Chestnut-mandibled Toucan", fact: "" },
  { name: "Blue-rumped Parrot", fact: "" },
  { name: "White-bellied Woodstar", fact: "" },
  { name: "Tawny-tufted Toucanet", fact: "" },
  { name: "Red-and-green Macaw", fact: "" },
  { name: "Buff-necked Ibis", fact: "" },
  { name: "Yellow-billed Cotinga", fact: "" },
  { name: "Grey-rumped Swiftlet", fact: "" },
  { name: "White-shouldered Ibis", fact: "" },
  { name: "Rufous-fronted Thornbird", fact: "" },
  { name: "Chestnut-winged Cuckoo", fact: "" },
  { name: "Blue-crowned Trogon", fact: "" },
  { name: "Black-spotted Barbet", fact: "" },
  { name: "White-whiskered Puffbird", fact: "" },
  { name: "Yellow-tufted Woodpecker", fact: "" },
  { name: "Grey-chinned Minivet", fact: "" },
  { name: "Rufous-tailed Scrub Robin", fact: "" },
  { name: "Brown-flanked Bush Warbler", fact: "" },
  { name: "Pale-crowned Cisticola", fact: "" },
  { name: "Black-throated Wattle-eye", fact: "" },
  { name: "Red-winged Pytilia", fact: "" },
  { name: "White-spotted Flufftail", fact: "" },
  { name: "Chestnut-backed Buttonquail", fact: "" },
  { name: "Golden-spectacled Warbler", fact: "" },
  { name: "Black-capped Social Weaver", fact: "" },
  { name: "Yellow-mantled Widowbird", fact: "" },
  { name: "Olive-headed Weaver", fact: "" },
  { name: "Purple-banded Sunbird", fact: "" },
  { name: "White-fronted Scops Owl", fact: "" },
  { name: "Buff-crested Bustard", fact: "" },
  { name: "Brown-headed Paradise Kingfisher", fact: "" },
  { name: "Rufous-bellied Kookaburra", fact: "" },
  { name: "Chestnut-breasted Cuckoo", fact: "" },
  { name: "Black-sided Flowerpecker", fact: "" },
  { name: "White-bellied Erpornis", fact: "" },
  { name: "Golden-fronted Leafbird", fact: "" },
  { name: "Tawny-breasted Honeyeater", fact: "" },
  { name: "Blue-faced Parrotfinch", fact: "" },
  { name: "Scarlet-backed Flowerpecker", fact: "" },
  { name: "Grey-headed Canary-Flycatcher", fact: "" },
  { name: "Red-capped Flowerpecker", fact: "" },
  { name: "Brown-throated Sunbird", fact: "" },
  { name: "Black-headed Bulbul", fact: "" },
  { name: "Crimson-winged Woodpecker", fact: "" },
  { name: "White-bellied Minivet", fact: "" },
  { name: "Orange-bellied Flowerpecker", fact: "" },
  { name: "Black-and-crimson Oriole", fact: "" },
  { name: "Rufous-winged Philentoma", fact: "" },
  { name: "Blue-winged Leafbird", fact: "" },
  { name: "Cream-vented Bulbul", fact: "" },
  { name: "Grey-hooded Broadbill", fact: "" },
  { name: "Dusky Broadbill", fact: "" },
  { name: "Green Broadbill", fact: "" },
  { name: "Silver-breasted Broadbill", fact: "" },
  { name: "Red-throated Barbet", fact: "" },
  { name: "Yellow-crowned Barbet", fact: "" },
  { name: "Golden-whiskered Barbet", fact: "" },
  { name: "Black-browed Barbet", fact: "" },
  { name: "White-chested Babbler", fact: "" },
  { name: "Rufous-tailed Tailorbird", fact: "" },
  { name: "Fluffy-backed Tit-babbler", fact: "" },
  { name: "Chestnut-rumped Babbler", fact: "" },
  { name: "Black-throated Babbler", fact: "" },
  { name: "Ferruginous Babbler", fact: "" },
  { name: "Striped Wren-Babbler", fact: "" },
  { name: "Marbled Wren-Babbler", fact: "" },
  { name: "Short-tailed Babbler", fact: "" },
  { name: "Brown Fulvetta", fact: "" },
  { name: "Mountain Fulvetta", fact: "" },
  { name: "Grey-cheeked Fulvetta", fact: "" },
  { name: "Golden-breasted Fulvetta", fact: "" },
  { name: "Black-browed Reed Warbler", fact: "" },
  { name: "Thick-billed Warbler", fact: "" },
  { name: "Striated Grassbird", fact: "" },
  { name: "Rufous-rumped Grassbird", fact: "" },
  { name: "Marsh Babbler", fact: "" },
  { name: "White-crested Laughingthrush", fact: "" },
  { name: "Chestnut-crowned Laughingthrush", fact: "" },
  { name: "Black-faced Laughingthrush", fact: "" },
  { name: "Scaly Laughingthrush", fact: "" },
  { name: "Streaked Laughingthrush", fact: "" },
  { name: "Blue-winged Laughingthrush", fact: "" },
  { name: "White-gorgeted Flycatcher", fact: "" },
  { name: "Rufous-chested Flycatcher", fact: "" },
  { name: "Verditer Flycatcher", fact: "" },
];
