// ── General bird pool ─────────────────────────────────────────────────────────
// Used for easy / medium modes. Mix of well-known, charismatic, and obscure.
const BIRDS = [

  // Africa
  { name: "Shoebill", fact: "Stands nearly 1.5 metres tall and stares at prey with both eyes forward like an owl — extremely unusual for a bird. It hunts lungfish by freezing motionless in swamps for hours, then striking with a bill that can decapitate its catch." },
  { name: "Secretary Bird", fact: "Kills snakes by stamping on them with feet that deliver a force five times its own body weight — fast enough that the snake cannot react. Despite being a raptor, it spends most of its life walking, covering up to 20 km a day on foot." },
  { name: "Hammerkop", fact: "Builds the largest nest of any bird relative to its size — a roofed fortress of sticks, mud and grass up to 1.5 metres across that can hold the weight of a grown adult. Pairs build up to five of these in a single year, often for no apparent reason." },
  { name: "Marabou Stork", fact: "Has a hollow leg bone connected to its lungs so it can use its legs as a radiator to cool blood in African heat. Its bald head and neck stay cleaner when plunged deep inside carcasses, and it can eat burning charcoal and old leather without apparent ill effect." },
  { name: "African Fish Eagle", fact: "The call of the African Fish Eagle is so iconic it is used as a generic 'Africa' sound effect in films set on other continents. It snatches fish from the surface with its talons while barely getting its feet wet, then flies off with a meal in under three seconds." },
  { name: "Lilac-breasted Roller", fact: "Gets its name from the spectacular rolling dive it performs during courtship — plummeting and twisting while calling loudly. It can see ultraviolet light, which reveals tracks and urine trails left by insects and lizards invisible to human eyes." },
  { name: "Southern Ground Hornbill", fact: "Lives in groups where only the dominant pair breeds, and helpers — including non-relatives — wait up to a decade for a chance to raise chicks. The group buries food caches and can remember locations for years. Individuals can live past 70." },
  { name: "Hoopoe", fact: "The female and chicks produce a foul-smelling liquid from their preen gland that coats the nest, deterring predators and bacteria. Despite the stench, it was considered sacred in ancient Egypt and appears in hieroglyphics. It also probes soil with its bill like a precision sewing machine." },
  { name: "Cape Sugarbird", fact: "Found only in South Africa's fynbos, it pollinates proteas so efficiently that the plants have evolved flowers matching the exact curve of its bill. The male's tail can be twice its body length and he carries it even while hovering in strong winds." },
  { name: "Ostrich", fact: "The largest living bird and the fastest running bird on Earth, reaching 70 km/h in a sprint. Its eye is bigger than its brain — each eyeball measures 5 cm across. Rather than burying its head in the sand, it lays its head flat on the ground to hide." },
  { name: "Saddle-billed Stork", fact: "One of Africa's tallest flying birds at up to 150 cm, with a bill so vivid — red, black and yellow with a yellow 'saddle' — that early explorers thought it must have been painted. Males and females are identical except for eye colour: males have brown eyes, females yellow." },
  { name: "African Skimmer", fact: "Flies low over rivers with its lower mandible slicing through the water like a plow blade. The moment it feels a fish, the upper bill snaps shut in a split second. Its lower mandible grows faster than the upper to compensate for constant wear from dragging through water." },
  { name: "Pel's Fishing Owl", fact: "One of the world's largest owls, specialising entirely in fish. Unlike other owls it has no sound-dampening feathers — waterproofing matters more than silence when hunting fish — and its feet have spiny scales for gripping slippery prey. Its call is a deep booming moan heard a kilometre away." },
  { name: "Hartlaub's Turaco", fact: "The only birds to have true red and green pigments in their feathers — most birds fake these colours with structure. Turacos make their own copper-based pigments called turacin (red) and turacoverdin (green) that dissolve slightly in water, giving the illusion of bleeding colour in heavy rain." },
  { name: "Superb Starling", fact: "A common East African bird so brilliantly coloured — metallic blue-green above, chestnut below, with a white chest band — that tourists often mistake it for an exotic rarity. Despite its looks it's a bold opportunist that will steal food from café tables." },
  { name: "Kori Bustard", fact: "Possibly the heaviest flying bird on Earth, with males reaching 19 kg. During courtship the male inflates its neck to balloon size and fans its white undertail feathers until it looks twice its normal size. It eats toxic plants and venomous snakes without apparent harm." },
  { name: "Grey Crowned Crane", fact: "The only crane that roosts in trees — its hind toe is long enough to grip branches. It stamps its feet while foraging to flush insects, and its golden crown of bristled feathers vibrates in response to sound, possibly acting as a resonator for its booming call." },
  { name: "Rosy-faced Lovebird", fact: "In cold desert nights pairs tuck their heads under each other's wings and sleep pressed together, regulating each other's body temperature. Females carry nesting material tucked into their rump feathers rather than in their bills — a method unique among parrots." },
  { name: "Black-and-white Casqued Hornbill", fact: "A large rainforest hornbill of Central Africa that relies on figs and uses its casque — a hollow ridge on the bill — to amplify its resonant calls through the forest. Pairs remain bonded for life and the male seals the female into the nest cavity with mud and droppings." },
  { name: "African Pitta", fact: "A jewel of the rainforest floor — glossy blue, green, red and black — yet so secretive that it was once considered rare. It is now known to be a common migrant that simply hides perfectly in leaf litter. It hammers snails against anvil stones to break the shells." },
  { name: "Martial Eagle", fact: "Africa's largest eagle, powerful enough to knock a grown person off their feet. It can spot prey from 5 km away and has been documented killing small antelopes, monitor lizards and young baboons. Its population has crashed due to persecution and habitat loss." },
  { name: "Bateleur", fact: "Spends up to eight hours a day airborne, covering 300–400 km while barely flapping. Its name is French for 'street performer' — a reference to its rocking, acrobatic flight. The bare red face skin flushes darker when the bird is agitated or excited." },
  { name: "Namaqua Sandgrouse", fact: "Males fly up to 80 km to a waterhole, wade in, and soak their specially adapted belly feathers — which can hold 15–20 ml of water like a sponge. They fly back and the chicks drink directly from the feathers. Chicks can do this from day one." },
  { name: "Long-crested Eagle", fact: "Its extraordinarily long floppy head plumes — up to 15 cm — give it a permanently surprised expression and bounce comically as it flies. Despite looking dramatic it is a specialist rodent hunter, eating almost nothing but voles and other small mammals." },
  { name: "Pennant-winged Nightjar", fact: "The breeding male grows two inner wing feathers that extend up to 50 cm beyond the wingtip as white trailing streamers. He flies with these huge pennants fluttering behind him at dusk to attract females. After breeding season he moults them off and looks like a completely different bird." },
  { name: "Black Heron", fact: "Hunts by spreading both wings into a perfect black umbrella over the water, creating a patch of shade. Fish swim into it seeking shelter from the sun, and the heron picks them off. It is the only animal known to create a tool entirely from its own body to lure prey." },
  { name: "Greater Honeyguide", fact: "The only bird known to actively guide humans to food. Using a distinctive chattering call and fluttering flight, it leads honey-hunters to bees' nests — sometimes over a kilometre — then waits for them to break the hive open before eating the wax and larvae left behind. The partnership is ancient enough to have its own traditional signals in Mozambique." },
  { name: "Long-tailed Widowbird", fact: "The male's tail feathers reach 50 cm — four times its body length — and he hauls them through the air in a slow, laboured display flight above the savannah. Scientists who glued on artificial extensions found those males attracted dramatically more females, confirming the tail is pure sexual advertising at an honest cost." },
  { name: "African Broadbill", fact: "Performs one of the strangest courtship displays in Africa: the male flies in tight circles around a branch so fast his wings create a mechanical purring sound, then suddenly freezes and puffs himself into a round blob to show off his vivid purple throat patch." },
  { name: "African Finfoot", fact: "An extremely shy waterbird that swims low in the water like a grebe but climbs into waterside vegetation to escape. The female carries newly hatched chicks in special pouches of skin under her wings while swimming — discovered by accident when a bird was spooked and chicks tumbled out." },
  { name: "Sunbird Asity", fact: "A Madagascan oddity distantly related to broadbills but looking exactly like a sunbird — a striking example of convergent evolution. The male has a vivid wattle of electric blue and green bare skin around the eye that inflates during breeding season and deflates completely afterwards." },
  { name: "Lappet-faced Vulture", fact: "The most dominant vulture at a carcass in Africa — other species wait for it to open the hide before they can feed. The bare red folds of skin on its face help it look intimidating. It eats skin, tendons and bone fragments that other scavengers cannot process." },
  { name: "Hooded Vulture", fact: "One of the smallest African vultures, with a thin bill perfectly sized for probing into crevices and eye sockets that larger vultures can't reach. It has recently learned to follow fishing trawlers and scavenge at rubbish dumps, but is still one of the fastest-declining birds in Africa." },
  { name: "Verreaux's Eagle", fact: "One of the most specialised predators on Earth — up to 98% of its diet is rock hyrax, a rabbit-sized mammal. So dependent on hyrax colonies that when they disappear from an area the eagles abandon their territory rather than switch prey. Pairs use the same cliff nest for decades, adding sticks each year until it is enormous." },
  { name: "Taita Falcon", fact: "A tiny torpedo-shaped falcon that nests exclusively on sheer cliff faces, including inside Batoka Gorge at Victoria Falls. Fewer than 200 are thought to exist globally, yet it is so fast and agile it regularly catches swifts — themselves masters of aerial speed." },
  { name: "White-fronted Bee-eater", fact: "Lives in extended family groups where non-breeding helpers assist the dominant pair — but also 'kidnaps' young from other pairs within the colony, harassing them until a fledgling abandons its own parents and follows its abductors, boosting the kidnapper's own reproductive success." },
  { name: "African Jacana", fact: "Walks on floating lily pads on extraordinarily long toes that spread its weight like snowshoes. Sex roles are reversed: females are larger, hold territories and mate with several males. Each male incubates eggs and rears chicks alone — tucking the tiny chicks under his wings and wading to safety with their legs dangling out." },
  { name: "Knysna Turaco", fact: "A brilliantly coloured forest turaco of South Africa's Garden Route whose emerald green plumage comes from turacoverdin, a copper-based pigment found in no other animal on Earth. It runs along branches with surprising speed and agility rather than flying between them." },
  { name: "African Openbill", fact: "Its bill has a permanent gap when closed — not a deformity but a precision tool. The edges of the mandibles meet only at the tip, forming curved forceps perfectly shaped for gripping and twisting open apple snail shells and freshwater mussels without crushing them." },
  { name: "Palm-nut Vulture", fact: "The only vulture that eats primarily plant material — it feeds mainly on the husks of oil palm and raphia palm fruits. This vegetarian diet allows it to thrive in dense forest where other vultures rarely venture. Despite being a vulture it also readily eats fish, frogs and crabs." },

  // Asia
  { name: "Indian Peafowl", fact: "The male's train isn't his tail — it's elongated back plumage. Each feather has an iridescent 'eye' made not from pigment but from nanostructures that reflect light differently at every angle. The train rattles and shimmers during display and produces infrasound below human hearing that females may sense through their feet." },
  { name: "Himalayan Monal", fact: "The national bird of Nepal, the male is arguably the most colourful bird in Asia — covered in metallic green, purple, copper and blue, with no two patches the same hue. It digs through deep snow with its heavy curved bill to reach roots and tubers at altitudes above 4,000 metres." },
  { name: "Red-crowned Crane", fact: "One of the rarest cranes on Earth, with fewer than 3,000 remaining. In Japanese culture it symbolises longevity and fidelity, appearing on the 1,000-yen note. Pairs bond for life and perform elaborate synchronised dances — leaping and calling in perfect unison — that strengthen the bond year after year." },
  { name: "Oriental Pied Hornbill", fact: "Like all hornbills, the male seals the female inside a tree hollow with mud and droppings, leaving only a slit through which he passes food for months. The female uses the enforced isolation to safely moult all her flight feathers at once — something she couldn't do while exposed to predators." },
  { name: "Sarus Crane", fact: "The world's tallest flying bird, standing up to 180 cm. Sacred in India and depicted in ancient Sanskrit literature as a symbol of faithful love, because pairs reputedly grieve when a partner dies. Farmers deliberately protect nesting Sarus cranes in rice paddies, believing harming one brings misfortune." },
  { name: "Indian Roller", fact: "The state bird of three Indian states, famous for its dazzling aerial display in which it rolls and tumbles to reveal brilliant turquoise underwings — colour invisible when the bird is perched. Farmers welcome it because it follows tractors to snatch exposed insects and earthworms." },
  { name: "Painted Stork", fact: "Feeds by wading with its partly open bill submerged and sweeping it side to side, snapping shut purely by touch the instant a fish brushes it. The faint pink flush on its wing tips deepens during breeding season — the only stork to change colour seasonally." },
  { name: "Indian Paradise Flycatcher", fact: "The male comes in two forms — white or chestnut — and grows two central tail feathers that stream up to 30 cm behind him. He fans and waves them during courtship while the female sits apparently unmoved, assessing how long he can maintain the performance." },
  { name: "Siberian Crane", fact: "Makes one of the longest migrations of any bird — breeding in remote Arctic Russia and wintering almost entirely at China's Poyang Lake. With fewer than 4,000 left, its survival hinges on a single wetland. It uses touch rather than sight to probe underwater for the plant roots it eats." },
  { name: "Great Hornbill", fact: "The hollow casque on the bill acts as a resonator for its deep booming call, which carries far through the dense forest. The male feeds the sealed-in female up to 150 times a day, passing food piece by piece through the narrow slit. Pairs stay together for life and can live over 50 years." },
  { name: "Brahminy Kite", fact: "Considered sacred in Bali, where it is the divine vehicle of Vishnu, and revered across Hindu and Buddhist cultures throughout Southeast Asia. It scavenges shorelines and rubbish dumps with equal comfort, but also hunts live prey — snatching fish, frogs and even bats with a sudden plunging strike." },
  { name: "Sri Lanka Frogmouth", fact: "One of the world's most perfectly camouflaged birds. By day it sits motionless on a mossy branch with its eyes slitted and bill raised, looking precisely like a broken stub of bark. It is endemic to Sri Lanka and the Western Ghats and was unknown to science until 1849." },
  { name: "Stork-billed Kingfisher", fact: "One of the largest kingfishers in Asia, with a bill so disproportionately huge — red, massive and cartoon-like — that it seems physically improbable. It dives into rivers to catch large fish but also eats lizards, frogs and small birds, waiting motionless on a branch before plunging." },
  { name: "Blue Pitta", fact: "A jewel of the forest floor — electric blue, orange and black — that is heard far more often than seen. It hops through leaf litter turning over dead leaves with its bill in search of earthworms. Males sing persistently at dawn from a favourite perch, but disappear into undergrowth almost instantly." },
  { name: "Jerdon's Courser", fact: "A nocturnal wader so rarely seen that it was believed extinct for over 80 years before being rediscovered in 1986 in a steep rocky gorge in India. It forages only at night on boulder-strewn streamsides and retreats to rocky crevices by day, making it almost impossible to survey." },
  { name: "Malabar Trogon", fact: "The male is crimson below and iridescent dark blue-green above, but sits so still in the forest shade that it vanishes despite its colours. Endemic to the Western Ghats and Sri Lanka, it nests in tree cavities it excavates itself, using its serrated bill like a saw." },
  { name: "Spoon-billed Sandpiper", fact: "Its spatula-shaped bill is unique among waders and acts like a sensitive metal detector, sweeping through soft mud and snapping shut on tiny invertebrates. Critically endangered, with perhaps only 500 remaining, it migrates from Arctic Russia to Bangladesh and Myanmar along a flyway that has lost most of its stopover wetlands." },
  { name: "Milky Stork", fact: "A coastal stork of mangroves and tidal mudflats in Southeast Asia that feeds with its bill partly open, feeling for fish and crabs by touch. Its population has plummeted as mangroves are cleared for aquaculture, and it now survives mainly in a handful of protected sites in Sumatra." },
  { name: "Bar-headed Goose", fact: "Regularly flies directly over the Himalayas at altitudes above 7,000 metres — sometimes passing over Everest. Its haemoglobin binds oxygen far more efficiently than that of lowland birds, and its heart rate during this extreme exertion is higher than any other bird ever measured." },
  { name: "Mandarin Duck", fact: "The male's courtship plumage includes a pair of orange 'sail' feathers that project upright from the wing — used purely for display and moulted immediately after the breeding season. Considered a symbol of marital fidelity in China and Japan, though pairs actually separate each year and choose new mates." },
  { name: "Walden's Hornbill", fact: "Critically endangered and confined to a handful of Philippine islands, it was named for an English ornithologist and is so rarely photographed that basic facts about its behaviour remain unknown. Its casque and bill are brighter yellow-orange in males, and pairs engage in noisy aerial chases through the forest canopy." },
  { name: "Bornean Bristlehead", fact: "Possibly the strangest bird in Borneo — a chunky black-and-red forest bird whose bare red head is studded with small fleshy knobs, giving it a warty, alien appearance. It has no close living relatives; its whole family contains just this one species. It travels in noisy flocks and the knobs' function remains unknown." },
  { name: "Wrinkled Hornbill", fact: "Has a deeply corrugated bill and casque that makes it look like it has been badly crumpled. Found only in the lowland rainforests of Borneo and the Malay Peninsula, it is heavily dependent on old-growth trees with cavities large enough to seal a female inside for incubation." },
  { name: "Gurney's Pitta", fact: "Once thought extinct, rediscovered in Thailand in 1986 and again in Myanmar in 2003. The male is a mosaic of deep blue, yellow and black. It lives in lowland rainforest that has been almost entirely logged, and surveys suggest only a few hundred individuals remain." },
  { name: "Philippine Eagle", fact: "One of the world's largest eagles, with a wingspan up to 220 cm and eyes described by researchers as 'almost human' in expressiveness. It hunts flying lemurs through dense canopy at speed. Critically endangered, with under 800 left, and the national symbol of the Philippines." },
  { name: "Palawan Peacock-Pheasant", fact: "The male carries an iridescent blue-green fan of tail feathers covered in metallic 'eyes', which he fans open and rocks from side to side during courtship while the female circles to examine each eye from every angle. Found only on the Philippine island of Palawan." },
  { name: "Storm's Stork", fact: "One of the world's rarest storks, with probably fewer than 500 remaining. Confined to undisturbed lowland rivers in Borneo, Sumatra and Malaysia, it nests in huge trees overhanging the water. Almost nothing is known about its breeding behaviour because it is so rarely observed." },
  { name: "Crested Serpent Eagle", fact: "Specialises almost entirely in snakes and lizards, using its broad rounded wings to slow-glide over the forest canopy while watching for prey below. When it spots a snake it drops and pins it with powerful feet before biting the back of the skull — immune to most snake venoms it encounters." },
  { name: "Cheer Pheasant", fact: "A long-tailed pheasant of steep Himalayan hillsides whose male has 18 tail feathers — more than any other pheasant. Its name comes from its call, a loud ringing 'chir-chir-chirwa', not its demeanour. It is so good at hiding in rocky scrub that locals describe it as 'impossible to find twice.'" },
  { name: "Satyr Tragopan", fact: "The male has a brilliant crimson breast studded with white spots like a polka-dot spotlight. During courtship he inflates two blue horns on his head and a bib of brilliant blue and red skin that expands to the size of a handkerchief — then suddenly flashes it at the female from behind a rock." },
  { name: "Temminck's Tragopan", fact: "Found high in the Eastern Himalayas, the male performs one of the most spectacular displays in the bird world: crouching low, spreading his spotted wings as a backdrop, and inflating an extraordinary patterned bib of blue, red and white skin that hangs down from his throat like a painted flag." },
  { name: "Green Peafowl", fact: "Larger and arguably more elegant than the Indian Peafowl, with iridescent green and bronze plumage and a neat, upright crest. Unlike its cousin, both sexes carry long train feathers. Once widespread across Southeast Asia, it has been hunted and its wetland habitat drained until only scattered populations remain." },
  { name: "Wilson's Bird-of-Paradise", fact: "Has a bare turquoise-blue crown — one of the only birds with genuinely blue skin rather than blue feathers. The male painstakingly clears the forest floor of every leaf before performing his display, creating a stage. The curling green tail wires are held in a tight spiral at rest and flung outward during display." },
  { name: "Wallace's Standardwing", fact: "Named for Alfred Russel Wallace, who discovered it on the island of Bacan in 1858 and wrote that it was 'more like a work of art than a natural production.' The male carries two long white breast plumes — the 'standards' — that he erects and vibrates while hanging upside down in a communal display tree." },
  { name: "Maleo", fact: "Lays eggs six times the size of a chicken egg in geothermal or sun-warmed sand, then abandons them. The chick digs out alone, tunnelling upward through half a metre of sand over several days, and emerges fully feathered and able to fly within hours — having received no parental care whatsoever." },
  { name: "Nicobar Pigeon", fact: "The closest living relative of the extinct Dodo and Rodrigues Solitaire — the sole survivor of a lineage of giant island pigeons. It has iridescent hackles of green, copper and blue cascading from its neck, and a small white tail. It travels in flocks between islands up to 400 km apart to find fruiting trees." },
  { name: "Black-naped Pheasant-Pigeon", fact: "A secretive ground-pigeon of Papua New Guinea's Fergusson Island, discovered only in 1882 and then not photographed alive in the wild until 2023, when camera traps finally captured it after an exhaustive community-led search. It lives in dense montane forest and walks rather than flies." },
  { name: "Halmahera Paradise Crow", fact: "A glossy blue-black bird related to birds-of-paradise, found only on the Indonesian island of Halmahera. The male has a vivid red iris and performs a hopping display in the forest understory. So little is known about it that researchers still don't fully understand its display or nesting behaviour." },
  { name: "Spot-billed Pelican", fact: "Has a distinctive pink and blue-spotted bill pouch used to scoop fish like a net. Unlike other pelicans it often breeds colonially in trees far from water, and groups fish cooperatively, beating the surface with their wings to herd shoals into shallow water before plunging their bills in unison." },
  { name: "Pied Kingfisher", fact: "The world's largest kingfisher that hovers. It can hang stationary over water for up to 30 seconds, vibrating its wings at 9 beats per second while scanning below, then plunges straight down. Because it doesn't need a perch over water, it can fish rivers and lakes with no overhanging trees at all." },

  // Australasia & New Zealand
  { name: "Cassowary", fact: "Has a blade-like inner claw up to 12 cm long that it uses to disembowel threats with a single kick. Despite being the world's most dangerous bird, it is a crucial rainforest gardener — the only animal large enough to swallow and disperse the seeds of over 150 tree species." },
  { name: "Kea", fact: "The world's only alpine parrot, and one of the most intelligent birds alive. Keas solve multi-step puzzles, play in snow for fun, and have been filmed dismantling car windscreen wipers and stealing wallets from tourists. They make decisions collectively and have been observed using probability to improve their odds." },
  { name: "Kiwi", fact: "The only bird with nostrils at the tip of its bill, used to sniff out earthworms underground like a mammal. Its feathers are more like coarse hair than plumage, and it has no visible tail. Its egg is proportionally the largest of any bird — up to 20% of the female's body weight." },
  { name: "Tawny Frogmouth", fact: "Not an owl — it's related to nightjars. By day it freezes motionless on a branch with its bill pointed upward and eyes almost closed, looking exactly like a broken stub of wood. The camouflage is so effective that researchers have walked within arm's reach without noticing it." },
  { name: "Superb Lyrebird", fact: "The world's greatest vocal mimic: it accurately reproduces chainsaws, car alarms, camera shutters, crying babies and other birds. The male spends years perfecting his display before breeding, and during courtship vibrates his extraordinary lace-like tail over his entire body like a shimmering silver veil." },
  { name: "Rifleman", fact: "New Zealand's smallest bird and one of its most ancient — sole survivor of a lineage that diverged from all other birds over 80 million years ago. The male is an electric iridescent green so vivid it seems to glow; the female is streaky brown. They chip insistently through bark in search of insects." },
  { name: "Laughing Kookaburra", fact: "The famous 'jungle laugh' is a territorial call used by family groups at dawn and dusk, often triggering neighbouring groups to call back in a domino effect. Despite the name it lives in dry woodland, not jungle. It kills snakes by carrying them high in the air and dropping them onto rocks." },
  { name: "Kakapo", fact: "The world's heaviest parrot and the only flightless one. Males gather on hilltop 'leks' and boom from bowl-shaped depressions in the ground — the infrasound travels for kilometres. It is so critically endangered that every individual has a name; intensive management has raised the population from 51 to over 200." },
  { name: "Satin Bowerbird", fact: "Males spend years collecting blue objects — bottle caps, pen lids, flowers, feathers — to decorate a stick bower. He arranges them carefully and has been caught stealing from neighbours. Females prefer males whose bowers contain the most blue items and who are best at replacing stolen ones." },
  { name: "Regent Bowerbird", fact: "The male is a startling black and golden-yellow, among the most vividly patterned birds in Australia. He makes a grey paint from a mix of saliva and chewed plant material, which he applies to the walls of his bower with a wad of bark used as a brush — one of the very few tool-using birds." },
  { name: "Tooth-billed Bowerbird", fact: "Instead of building a decorated bower, the male clears a patch of forest floor and tiles it with large fresh leaves, all placed upside down with their pale undersides facing up. He replaces them as they wilt. The 'tooth' on his bill is used to cut these leaves from branches." },
  { name: "Vogelkop Bowerbird", fact: "Builds the most structurally complex bower of any animal: a conical thatched hut up to a metre tall with a doorway, fronted by a lawn of moss decorated with coloured piles of fruit, flowers, beetles and fungi — each colour group in its own cluster. Different males develop distinct aesthetic styles." },
  { name: "Raggiana Bird-of-Paradise", fact: "The national symbol of Papua New Guinea, its cascading orange-red plumes were so sought-after for European hats in the 19th century that early naturalists suspected the bird had no feet, since specimens arrived without them. Males compete in communal trees, displaying simultaneously to silent females." },
  { name: "King Bird-of-Paradise", fact: "The smallest bird-of-paradise and arguably the most extravagant. The male has two wiry tail shafts that end in spiralling green discs, which he swings like pendulums. He displays by hanging upside down and expanding his fan-shaped flank plumes into perfect white circles." },
  { name: "Western Parotia", fact: "Grows six wire-like head plumes tipped with reflective discs. During courtship it transforms itself into a black ballerina — fluffing its flank feathers into a skirt and pivoting in precise circles for minutes at a time. The breast feathers are nanoscale structures that reflect light like a supermatte black." },
  { name: "King-of-Saxony Bird-of-Paradise", fact: "The male's two head plumes — each twice his body length, decorated with a row of enamel-blue flags — have no counterpart in the animal kingdom. Early scientists who received specimens refused to believe they were real and assumed taxidermists had added them from some other creature." },
  { name: "Blue Bird-of-Paradise", fact: "Performs its display entirely upside down, hanging from a branch and slowly expanding two long blue tail wires while swaying rhythmically. The black breast feathers part to reveal a pulsing iridescent blue oval. The entire display looks like something from a fever dream." },
  { name: "Twelve-wired Bird-of-Paradise", fact: "The flank feathers end in 12 bare wire-like filaments that the male repeatedly presses against the face of the female while displaying. Scientists still don't fully understand why — it may be a tactile assessment or a way of forcing her to keep her eyes on him." },
  { name: "Magnificent Riflebird", fact: "The male stretches his wings into a perfect arc and bobs his head to flash his iridescent throat, which seems to glow from within. The wing feathers are shaped to produce a sharp rasping sound as he raises them. Females have been observed mimicking this display themselves." },
  { name: "Victoria Crowned Pigeon", fact: "The world's largest pigeon — roughly the size of a turkey — and the only one with a permanent crest. The fan of lacy blue-grey feathers tipped with white is raised in alarm, lowered in submission, and waved in courtship. Males boom deeply like a large drum when territorial." },
  { name: "Palm Cockatoo", fact: "The only non-human animal known to use a tool for a musical purpose: the male picks up a stick or nut and drums it rhythmically against a hollow tree to attract females — producing a beat. Each male has his own consistent tempo and drumming style, similar to how human musicians develop a personal feel." },
  { name: "Gang-gang Cockatoo", fact: "The male has a vivid scarlet head and crest that wobbles as he feeds — looking permanently perplexed. It makes a distinctive sound described as a wine cork being pulled from a bottle. Pairs are devoted and groom each other constantly; males help incubate and brood the chicks through the night." },
  { name: "Glossy Black-Cockatoo", fact: "The quietest and most docile of Australia's black cockatoos. Females are flecked with yellow-orange patches that disappear entirely after their first moult into adult plumage, making females look almost identical to males. It feeds almost exclusively on the seeds of one or two species of sheoak." },
  { name: "Yellow-tailed Black-Cockatoo", fact: "Flocks of these large, wailing birds drifting through eucalyptus forests are one of Australia's most atmospheric sounds. They rip apart tree branches with their powerful bills to reach wood-boring beetle larvae — leaving the forest littered with debris that reveals where they've been feeding." },
  { name: "Swift Parrot", fact: "One of only three migratory parrots in the world. It breeds only in Tasmania and winters on the Australian mainland, crossing 300 km of ocean twice a year. Critically endangered — its entire population depends on the Tasmanian blue gum for nesting and sugar gliders have learned to raid its nests." },
  { name: "Orange-bellied Parrot", fact: "One of the rarest birds on Earth, with fewer than 50 adults surviving in the wild. It breeds only in a tiny area of southwest Tasmania and winters on the mainland. Despite an intensive captive breeding and release programme, it remains critically endangered and has not recovered." },
  { name: "Pesquet's Parrot", fact: "Has a bare red face like a vulture — unusual in parrots, but an adaptation for eating sticky figs without getting feathers hopelessly gummed. It is sometimes called the Dracula Parrot for its black-and-red plumage and gothic appearance. Found only in New Guinea's montane forests." },
  { name: "Eclectus Parrot", fact: "The male is vivid green; the female is brilliant red and blue. So different are they that ornithologists classified them as separate species for 150 years. The female controls a hollow tree cavity and may have several males bringing her food simultaneously — while she decides which to mate with." },
  { name: "Emu", fact: "Australia's largest bird is flightless but can run at 50 km/h. The male incubates the eggs and raises the chicks alone, not eating or drinking for up to 56 days during incubation — losing a third of his body weight. Emus can swim across rivers and have been known to travel 1,000 km following rain." },
  { name: "Wedge-tailed Eagle", fact: "Australia's largest bird of prey, with a wingspan up to 2.3 metres. It can soar for hours without a wingbeat, rising on thermals to altitudes where it disappears from sight. Once persecuted as a livestock killer, it was legal to shoot them until 1974 in Western Australia — with millions killed." },
  { name: "Australian Brushturkey", fact: "Builds a mound of rotting vegetation up to 4 metres tall and monitors the internal temperature obsessively, adding or removing material to maintain exactly 33°C. The male uses his bill as a thermometer accurate to half a degree. Chicks hatch fully developed and must dig out alone through a metre of compost." },
  { name: "Malleefowl", fact: "Like the Brushturkey, it builds a compost incubator — but in a much drier environment where decomposing material is scarce. A pair spends 11 months of the year maintaining their mound, opening it each morning to release heat and closing it each afternoon to retain warmth as outside temperatures plunge." },
  { name: "Plains-wanderer", fact: "Looks like a quail but is actually the sole member of an ancient lineage with no close relatives. The female is more boldly patterned than the male and holds the territory while the male incubates eggs and raises chicks alone. It sits perfectly still when threatened, trusting its camouflage, and is critically endangered." },
  { name: "Night Parrot", fact: "Australia's most mysterious bird — widely thought extinct for over a century before being photographed alive in 2013. It inhabits remote spinifex grasslands, flies only at night, and is so secretive that almost nothing is known about its ecology. Every confirmed sighting is considered a significant event." },
  { name: "Gouldian Finch", fact: "Comes in three naturally occurring colour forms — red-faced, black-faced and yellow-faced — that determine personality as well as looks. Pairs choose mates partly based on face colour because mismatched pairs produce more stressed offspring. The young are born with blue phosphorescent spots inside their mouths to guide parents feeding them in dark nests." },
  { name: "Splendid Fairywren", fact: "The male is an implausibly vivid cobalt blue, but maintains a 'harem' of dull brown females and helpers. Most chicks in any nest are fathered by males from neighbouring territories — the female secretly mates with better-looking males while her social partner provides all the parental care." },
  { name: "Noisy Scrubbird", fact: "Once thought extinct, rediscovered in 1961 in a tiny patch of dense coastal scrub in Western Australia. The male's territorial call is so loud it causes physical pain at close range. It is almost entirely flightless, running through low vegetation like a mouse, and rarely emerges into the open." },
  { name: "Powerful Owl", fact: "Australia's largest owl, with eyes so large and forward-facing it has unusually good binocular depth perception for hunting through cluttered forest. It often roosts during the day clutching the previous night's prey — sometimes a whole ringtail possum — in one foot, resuming the meal after dark." },
  { name: "Apostlebird", fact: "Lives in stable groups of around 12 birds — hence the name — in which all members share incubation and chick-rearing duties. The group makes group decisions about when to move, always roosting together in a tight bundle. They are extremely bold and will steal food from picnickers." },
  { name: "Chowchilla", fact: "A large ground-thrush of Queensland's rainforest whose explosive call — a piercing 'chow-chilla' duet between paired birds — erupts at dawn and can be heard over 500 metres away. It spends its days raking through leaf litter with both feet simultaneously, like someone frantically shuffling backwards." },
  { name: "Takahe", fact: "Believed extinct for 50 years before being rediscovered in a remote New Zealand valley in 1948. This large, flightless rail has powerful blue-green plumage and a massive red bill. Intensive conservation management — including predator control and egg fostering — has slowly rebuilt the population to over 500." },
  { name: "Wrybill", fact: "The only bird in the world with a bill that curves sideways — always to the right. It uses this asymmetric tool to probe under stones in riverbeds for insect larvae. It breeds only in New Zealand's South Island braided rivers and migrates to North Island estuaries in winter." },
  { name: "Black Stilt", fact: "The world's rarest wading bird, with fewer than 200 remaining. Found only in New Zealand's South Island braided rivers, it has been devastated by introduced predators. It is the focus of a captive breeding and headstarting programme that hand-raises chicks and releases them before predators learn to target them." },
  { name: "New Zealand Bellbird", fact: "When Captain Cook landed in New Zealand, the dawn chorus of bellbirds was so loud that sailors woke in astonishment, describing it as almost deafeningly beautiful — 'the most melodious wild music I have ever heard.' The female has a thin white whisker stripe; the male's head is a deep iridescent purple-green." },
  { name: "Hihi", fact: "The only bird that mates face-to-face, like humans. Males are highly aggressive and females often struggle to escape them — leading to conservation managers introducing rubber toys and distractions at nest boxes to give females control over mating. Males have disproportionately large testes for a songbird." },
  { name: "Kokako", fact: "Has one of the most haunting calls in the bird world — a slow, organ-like duet between pairs that carries through dense New Zealand forest at dawn. The blue facial wattles droop like a sad clown's cheeks, but the voice is extraordinary: researchers have described it as sounding like 'a sad monk.'" },
  { name: "Saddleback", fact: "Named for the chestnut 'saddle' across its back, contrasting with jet-black plumage. It has tiny vestigial wings almost useless for sustained flight. New Zealand's early forests were so safe that flightlessness evolved multiple times — then cats, stoats and rats arrived and nearly wiped it out." },
  { name: "Kaka", fact: "A forest parrot of New Zealand that uses its flexible tongue to extract nectar and its powerful bill to rip apart dead wood for grubs. Males and females have entirely different roles: males feed females during incubation, sometimes travelling kilometres to find food and returning to pass it mouth-to-mouth." },
  { name: "Weka", fact: "A flightless New Zealand rail with the boldness of a small terrier. It will steal shiny objects from campsites, untie bootlaces and investigate anything edible with fearless curiosity. It's an effective predator of small lizards and invertebrates, and has colonised offshore islands — sometimes too enthusiastically." },
  { name: "New Zealand Dotterel", fact: "One of New Zealand's rarest shorebirds, with two distinct populations so different in behaviour that they were once considered separate species. The northern population nests on beaches; the southern population nests only on the summit of Stewart Island, a 10 km hike from the coast." },
  { name: "Logrunner", fact: "An Australian rainforest bird that forages by bracing on its stiff spine-tipped tail and using both feet simultaneously to rake leaf litter aside with violent backwards kicks — creating a characteristic rustling sound heard throughout the forest floor. Pairs duet loudly each morning to announce their territory." },

  // Europe
  { name: "Bearded Vulture", fact: "Deliberately dyes its white feathers orange-red by bathing in iron-rich mud — the only bird known to intentionally colour itself. It subsists almost entirely on bones, dropping them from heights of up to 80 metres onto rocks to shatter them, then swallowing the fragments whole." },
  { name: "European Bee-eater", fact: "Catches bees and wasps in the air by sight, then beats them against a branch to discharge the sting and squeezes out the venom sac before swallowing. A single pair can catch 250 bees a day. Pairs are often assisted by 'helpers' — older offspring who forgo breeding to help raise younger siblings." },
  { name: "Common Kingfisher", fact: "Dives into water at up to 40 km/h with eyes closed, judging the fish's refracted position from above the surface. The bill is shaped like an asymmetric wedge — wider at the tip — to enter water without splashing. Engineers studied kingfisher anatomy to redesign the nose of Japan's Shinkansen bullet train." },
  { name: "Atlantic Puffin", fact: "Can carry over 60 fish crosswise in its bill at once — the record is 83. The tongue has backward-pointing spines that pin each fish against the palate, freeing the bill to open and catch more. It digs its nest burrow with its bill, sometimes excavating a metre-long tunnel." },
  { name: "Great Bustard", fact: "The world's heaviest flying bird, with males reaching 21 kg. During courtship the male inflates his neck, fans his tail over his back, and flips his wing feathers inside-out to become an implausible white powder-puff of froth — visible from over a kilometre. Females are less than a third the male's weight." },
  { name: "White-tailed Eagle", fact: "Europe's largest eagle, with a wingspan of up to 2.4 metres. Extinct in Britain for over a century before reintroduction. It was once believed to steal lambs, leading to extermination campaigns — though it is primarily a fish eagle that also takes waterbirds and carrion." },
  { name: "Eurasian Bittern", fact: "Its booming call — a deep, resonant pulse heard up to 5 km away — is made by inflating the oesophagus as a resonating chamber. When alarmed it freezes with bill pointing straight up, striped neck blending with surrounding reed stems so perfectly that it becomes invisible even in an open reedbed." },
  { name: "Dalmatian Pelican", fact: "The world's largest pelican and one of the heaviest flying birds, weighing up to 15 kg. The curly feathers on its head and the vivid orange-red pouch in breeding condition make it the most striking of all pelicans. Fewer than 12,000 remain, mostly in eastern Europe and Central Asia." },
  { name: "Eurasian Eagle Owl", fact: "One of the world's largest owls, capable of killing deer fawns, foxes and other raptors. Its orange eyes are fixed — it cannot move them in their sockets — so it compensates with a neck that rotates 270 degrees. Pairs hoot as a duet, and can be heard on still nights from 4 km away." },
  { name: "Great Grey Shrike", fact: "A predatory songbird that impales beetles, small mammals and even small birds on thorns or barbed wire — creating a 'larder' to return to later, or to display its hunting prowess to females. The larder's contents also preserve in cold weather, providing food stores through harsh winters." },
  { name: "Wallcreeper", fact: "Creeps up sheer cliff faces with the nimble confidence of a butterfly, constantly flicking its crimson wings in nervous little bursts. It nests on vertical rock faces in the Alps and Himalayas at altitudes above 3,000 metres, descending to lower gorges and old buildings in winter." },
  { name: "Snow Bunting", fact: "One of the most northerly-breeding birds on Earth, nesting in rock crevices on Svalbard and Arctic Greenland where snow can fall in any month. The male arrives on the Arctic breeding grounds up to five weeks before the female, enduring temperatures below -30°C to secure the best territories." },
  { name: "Eurasian Dotterel", fact: "Sex roles are completely reversed: the female is larger and more boldly patterned, arrives on the breeding grounds first, courts the male, then lays the eggs and leaves. The male incubates and raises the chicks entirely alone. Females sometimes mate with multiple males in the same season." },
  { name: "Ruff", fact: "Males come in three distinct forms — dark-ruffed 'independents', pale 'satellites' and small female-mimicking 'faeders' — that use completely different mating strategies. Satellites cooperate with independents at leks rather than compete with them, gaining matings through proximity. The female is called a Reeve." },
  { name: "Red Kite", fact: "Has a forked tail it uses like a rudder, banking and wheeling in slow, effortless circles. In medieval London, kites were so numerous they scavenged meat from butchers' stalls and even snatched food from children's hands. Poisoned to extinction in England, then spectacularly reintroduced in the 1990s." },
  { name: "Eurasian Roller", fact: "Named for the male's spectacular tumbling courtship flight, in which he climbs steeply and then rolls and dives while calling loudly. The electric blue of its wings is invisible when perched but explodes into view on takeoff. It nests in holes and is absent from most of its former range due to pesticide use." },
  { name: "Wryneck", fact: "Can twist its head almost 180 degrees like an owl — giving it its name. When caught in the hand it hisses, puffs up and rotates its head in slow spirals, mimicking a snake. Unlike woodpeckers it cannot excavate its own nest, instead taking over natural holes or evicting other species." },
  { name: "Eurasian Spoonbill", fact: "Swings its spatulate bill from side to side through shallow water in a scything motion, snapping shut by touch the instant it contacts a small fish or invertebrate. Chicks hatch with a straight bill that only develops the spoon shape as they grow. They feed through their parents' bill like a chute." },
  { name: "Black Woodpecker", fact: "Europe's largest woodpecker, the size of a crow, which hammers dead trees so ferociously it can excavate a hole in minutes. Its excavations open up cavities used by dozens of other forest species including owls, ducks, and flying squirrels. A single tree with a Black Woodpecker hole becomes a hub of forest biodiversity." },
  { name: "Hawfinch", fact: "Has the most powerful bill of any European songbird, capable of crushing cherry stones with a force of up to 70 kg — roughly what you'd feel standing on a scale. The bill's interior is lined with a grooved pad for gripping slippery seeds, and the jaw muscles account for a third of its total body weight." },
  { name: "Penduline Tit", fact: "Builds one of the most intricate nests in Europe: a purse-shaped bag woven from plant fibres and willow down, hung from a thin branch over water with a false entrance as a decoy. The real entrance is a closeable flap. Building takes two weeks and uses up to 10,000 individual fibres." },
  { name: "White-winged Snowfinch", fact: "Lives year-round at Alpine altitudes above the treeline, often above 2,500 metres, including in deep winter when its habitat is buried under metres of snow. It forages around ski lifts and mountain huts, having learned to exploit human food waste as a winter survival strategy." },
  { name: "Cinereous Vulture", fact: "Europe's and Asia's largest bird of prey, with a wingspan of nearly 3 metres. Unlike most vultures it prefers to eat the dry skin, tendons and ligaments that others ignore, using its massive hooked bill. A single bird can consume 1.5 kg of food in one sitting." },
  { name: "Common Firecrest", fact: "One of Europe's smallest birds at 5–6 grams, but among its most vivid — the male has a dazzling crown of orange, yellow and black stripes. It hovers briefly while gleaning insects from the tips of spruce needles, and can survive sub-zero temperatures by roosting communally and entering daily torpor." },
  { name: "Bluethroat", fact: "The male's throat is a vivid mosaic of blue, orange and white that varies between subspecies. It is one of the finest mimics in Europe, weaving the songs of dozens of other species into its own. It hops on the ground rather than perching and prefers thick cover close to water." },
  { name: "Pygmy Cormorant", fact: "The smallest cormorant in the world, barely larger than a Mallard. It dives in shallow freshwater lakes and rivers, often submerging completely in less than a metre of water. Its feathers are not fully waterproof, so after each diving session it stands with wings spread to dry, like all cormorants." },
  { name: "Eurasian Scops Owl", fact: "A tiny migratory owl that summers in southern Europe and winters in Africa. Its advertising call — a monotonous, repetitive 'toop' repeated for hours — carries up to 800 metres but is so consistent that it is easy to walk past the calling bird without ever pinpointing it." },
  { name: "Tengmalm's Owl", fact: "Nests only in old Black Woodpecker holes in boreal forest. The female sits so tight on eggs that she can be lifted off the nest by hand. The male caches food around the nesting hole, and in good vole years provides so much prey that some food rots before being eaten." },
  { name: "Great Snipe", fact: "Males gather at leks and display at night with rapid bill-snapping, tail-fanning and wing-shivering displays, competing in groups of up to 20. They have been recorded making the fastest unassisted migration flight of any bird — 7,000 km in 59 hours without stopping." },
  { name: "Eurasian Woodcock", fact: "Has eyes set so far back on its head it has a wider field of vision behind it than in front, allowing it to watch for predators while probing soil with its flexible bill tip. Males fly a regular 'roding' patrol circuit at dusk, calling with a peculiar frog-like croak, to claim territory." },

  // North America
  { name: "Arctic Tern", fact: "Migrates from the Arctic to the Antarctic and back every year — up to 90,000 km round trip. Over a 30-year lifespan it covers the equivalent of three trips to the Moon and back. It sees more daylight than any other creature on Earth, spending both Arctic and Antarctic summers in perpetual sun." },
  { name: "Peregrine Falcon", fact: "The fastest animal on Earth in a hunting stoop, exceeding 390 km/h. It strikes prey with a half-closed fist to avoid breaking its own feet on impact. Special baffles in its nostrils reduce the air pressure entering its lungs — without them, the impact of breathing at that speed would be fatal." },
  { name: "Snowy Owl", fact: "Can pinpoint and plunge into a lemming moving under 30 cm of compacted snow using hearing alone. In boom years for lemmings a pair may raise 11 chicks; in lean years they don't breed at all. Females have more dark markings than males, and fully white individuals are almost always old males." },
  { name: "Greater Roadrunner", fact: "Runs at 32 km/h and regularly kills rattlesnakes by seizing the head and slamming it against a rock. On cold desert mornings it spreads its back feathers to expose a patch of dark skin to the sun, using its own body as a solar panel to rewarm itself before it can function properly." },
  { name: "Clark's Nutcracker", fact: "Caches up to 98,000 pine seeds across hundreds of locations each autumn and can retrieve most of them months later under metres of snow. This spatial memory is so remarkable it has reshaped mountain pine forests — whitebark pines cannot regenerate without the nutcracker replanting their seeds." },
  { name: "Burrowing Owl", fact: "Actively 'farms' food by spreading mammal dung around its burrow entrance to attract dung beetles, then eats the beetles. Inside the burrow, when threatened, it mimics the sound of a rattlesnake — a hissing buzz that predators recognise, deterring them from investigating the hole." },
  { name: "Common Loon", fact: "Its haunting wail carries 10 km across still water. Eyes turn blood-red in breeding season. It is so perfectly adapted for diving — bones nearly solid, feet set far back — that it is almost unable to walk on land, pushing itself along on its belly. It can dive to 60 metres for fish." },
  { name: "Osprey", fact: "The only hawk that dives feet-first into water to catch fish. Its outer toe is reversible, allowing it to grip fish with two toes in front and two behind. It always rotates the fish head-forward before flying — reducing aerodynamic drag. Almost always found near water, on every continent except Antarctica." },
  { name: "Anna's Hummingbird", fact: "During its courtship dive, the male accelerates to 385 body-lengths per second — proportionally the fastest movement ever recorded in a vertebrate. At the bottom of the dive he produces a sharp chirp from his tail feathers, not his syrinx. He can sing through his nose while his throat is puffed up displaying." },
  { name: "Bobolink", fact: "The only North American land bird that is entirely black below and white above — the reverse of almost every other bird. Migrates 20,000 km to Argentina and back, navigating partly by detecting Earth's magnetic field using magnetite crystals in its head. Its bubbling song sounds like R2-D2." },
  { name: "Red Knot", fact: "Migrates from the Arctic to Tierra del Fuego and back — 30,000 km a year — making it one of the longest migrations of any bird relative to body size. Each spring it stops on Delaware Bay to gorge on horseshoe crab eggs, nearly doubling its weight in two weeks before the final push north." },
  { name: "Limpkin", fact: "Its screaming wail — described as the sound of someone being murdered in a swamp — was used as the Hippogriff's call in Harry Potter films and features as various monster sounds in Hollywood productions. In reality it is a shy wetland bird that specialises in extracting apple snails with a slightly twisted bill." },
  { name: "Snail Kite", fact: "Has evolved a thin, sharply hooked bill as a single-purpose tool for extracting apple snails from their shells — a technique it performs faster than any other predator. So specialised is it that when apple snail populations crash, snail kites also crash in numbers and their range contracts dramatically." },
  { name: "American Dipper", fact: "The only truly aquatic songbird in North America. It walks and swims underwater on river bottoms, gripping stones with strong toes while hunting for invertebrates. It has a third eyelid (nictitating membrane) that turns green when submerged, helping it see underwater, and a flap that closes its nostrils when diving." },
  { name: "Harlequin Duck", fact: "" },
  { name: "Painted Bunting", fact: "" },
  { name: "Scissor-tailed Flycatcher", fact: "" },
  { name: "Long-billed Curlew", fact: "" },
  { name: "Whooping Crane", fact: "" },
  { name: "California Condor", fact: "" },
  { name: "Vermilion Flycatcher", fact: "" },
  { name: "Phainopepla", fact: "" },
  { name: "Elf Owl", fact: "" },
  { name: "Elegant Trogon", fact: "" },
  { name: "Thick-billed Parrot", fact: "" },
  { name: "Marbled Murrelet", fact: "" },
  { name: "Western Grebe", fact: "" },
  { name: "Spruce Grouse", fact: "" },
  { name: "Tufted Puffin", fact: "" },
  { name: "Rhinoceros Auklet", fact: "" },
  { name: "Ivory Gull", fact: "" },
  { name: "Ross's Gull", fact: "" },
  { name: "Steller's Sea Eagle", fact: "" },
  { name: "Bristle-thighed Curlew", fact: "" },
  { name: "Kirtland's Warbler", fact: "" },
  { name: "Prothonotary Warbler", fact: "" },
  { name: "Gunnison Sage-Grouse", fact: "" },
  { name: "Roseate Spoonbill", fact: "" },

  // Central America & Caribbean
  { name: "Resplendent Quetzal", fact: "" },
  { name: "Turquoise-browed Motmot", fact: "" },
  { name: "Keel-billed Toucan", fact: "" },
  { name: "Harpy Eagle", fact: "" },
  { name: "Sunbittern", fact: "" },
  { name: "Bee Hummingbird", fact: "" },
  { name: "Wire-tailed Manakin", fact: "" },
  { name: "Club-winged Manakin", fact: "" },
  { name: "Amazonian Umbrellabird", fact: "" },
  { name: "Spectacled Owl", fact: "" },
  { name: "Sungrebe", fact: "" },
  { name: "Agami Heron", fact: "" },
  { name: "Zigzag Heron", fact: "" },
  { name: "Snowcap", fact: "" },
  { name: "Royal Flycatcher", fact: "" },
  { name: "Purple-crowned Fairy", fact: "" },
  { name: "Fiery-throated Hummingbird", fact: "" },
  { name: "Great Curassow", fact: "" },
  { name: "Lovely Cotinga", fact: "" },
  { name: "Snowy Cotinga", fact: "" },

  // South America
  { name: "Andean Condor", fact: "" },
  { name: "Hoatzin", fact: "" },
  { name: "Cock-of-the-rock", fact: "" },
  { name: "Horned Screamer", fact: "" },
  { name: "Jabiru", fact: "" },
  { name: "Inca Tern", fact: "" },
  { name: "Emperor Penguin", fact: "" },
  { name: "Rockhopper Penguin", fact: "" },
  { name: "Macaroni Penguin", fact: "" },
  { name: "Magellanic Penguin", fact: "" },
  { name: "Torrent Duck", fact: "" },
  { name: "Oilbird", fact: "" },
  { name: "Capuchinbird", fact: "" },
  { name: "Purple-breasted Cotinga", fact: "" },
  { name: "Banded Cotinga", fact: "" },
  { name: "Long-wattled Umbrellabird", fact: "" },
  { name: "Common Potoo", fact: "" },
  { name: "Great Potoo", fact: "" },
  { name: "Pale-winged Trumpeter", fact: "" },
  { name: "Giant Antpitta", fact: "" },
  { name: "Coppery-chested Jacamar", fact: "" },
  { name: "Rufescent Tiger Heron", fact: "" },
  { name: "Titicaca Grebe", fact: "" },
  { name: "James's Flamingo", fact: "" },
  { name: "Puna Flamingo", fact: "" },
  { name: "Hooded Grebe", fact: "" },
  { name: "Giant Coot", fact: "" },
  { name: "Wattled Curassow", fact: "" },
  { name: "Maguari Stork", fact: "" },
  { name: "Toco Toucan", fact: "" },

  // Seabirds & Polar
  { name: "Wandering Albatross", fact: "" },
  { name: "Waved Albatross", fact: "" },
  { name: "Light-mantled Albatross", fact: "" },
  { name: "Southern Giant Petrel", fact: "" },
  { name: "Snow Petrel", fact: "" },
  { name: "Blue-footed Booby", fact: "" },
  { name: "Red-footed Booby", fact: "" },
  { name: "Magnificent Frigatebird", fact: "" },
  { name: "White Tern", fact: "" },
  { name: "South Polar Skua", fact: "" },
  { name: "Long-tailed Jaeger", fact: "" },
  { name: "Swallow-tailed Gull", fact: "" },
  { name: "Sooty Shearwater", fact: "" },
  { name: "Manx Shearwater", fact: "" },
  { name: "Wilson's Storm Petrel", fact: "" },
  { name: "Red-billed Tropicbird", fact: "" },
  { name: "White-tailed Tropicbird", fact: "" },
  { name: "Abbott's Booby", fact: "" },
  { name: "Masked Booby", fact: "" },
  { name: "Brown Noddy", fact: "" },
  { name: "Christmas Frigatebird", fact: "" },

  // Owls & Nightbirds
  { name: "Great Grey Owl", fact: "" },
  { name: "Blakiston's Fish Owl", fact: "" },
  { name: "Verreaux's Eagle Owl", fact: "" },
  { name: "Crested Owl", fact: "" },
  { name: "Long-eared Owl", fact: "" },
  { name: "Barn Owl", fact: "" },
  { name: "Papuan Frogmouth", fact: "" },
  { name: "Standard-winged Nightjar", fact: "" },
  { name: "Lyre-tailed Nightjar", fact: "" },
  { name: "Pharaoh Eagle Owl", fact: "" },

];

// ── Hard-mode bird pool ───────────────────────────────────────────────────────
// Compound hyphenated names that match the SNEAKY fake-name generator style.
const HARD_BIRDS = [
  { name: "Yellow-rumped Warbler", fact: "" },
  { name: "Black-crowned Night Heron", fact: "" },
  { name: "Red-tailed Hawk", fact: "" },
  { name: "White-throated Sparrow", fact: "" },
  { name: "Blue-winged Teal", fact: "" },
  { name: "Golden-fronted Woodpecker", fact: "" },
  { name: "Red-breasted Nuthatch", fact: "" },
  { name: "Yellow-bellied Sapsucker", fact: "" },
  { name: "Golden-crowned Kinglet", fact: "" },
  { name: "Black-bellied Plover", fact: "" },
  { name: "White-crowned Sparrow", fact: "" },
  { name: "Chestnut-backed Chickadee", fact: "" },
  { name: "Rufous-tailed Hummingbird", fact: "" },
  { name: "Black-backed Woodpecker", fact: "" },
  { name: "Olive-backed Sunbird", fact: "" },
  { name: "White-bellied Sea Eagle", fact: "" },
  { name: "Rufous-crowned Sparrow", fact: "" },
  { name: "Yellow-billed Oxpecker", fact: "" },
  { name: "Blue-naped Mousebird", fact: "" },
  { name: "Chestnut-sided Warbler", fact: "" },
  { name: "Red-faced Cormorant", fact: "" },
  { name: "White-winged Crossbill", fact: "" },
  { name: "Black-headed Grosbeak", fact: "" },
  { name: "Yellow-fronted Canary", fact: "" },
  { name: "Rufous-bellied Niltava", fact: "" },
  { name: "Purple-backed Thornbill", fact: "" },
  { name: "Blue-faced Honeyeater", fact: "" },
  { name: "Red-necked Phalarope", fact: "" },
  { name: "White-cheeked Pintail", fact: "" },
  { name: "Tawny-flanked Prinia", fact: "" },
  { name: "Golden-backed Weaver", fact: "" },
  { name: "Black-winged Stilt", fact: "" },
  { name: "Buff-fronted Owl", fact: "" },
  { name: "Yellow-throated Longclaw", fact: "" },
  { name: "White-headed Vulture", fact: "" },
  { name: "Red-chested Swallow", fact: "" },
  { name: "Blue-spotted Wood Dove", fact: "" },
  { name: "Pale-billed Woodpecker", fact: "" },
  { name: "Black-throated Mango", fact: "" },
  { name: "White-tipped Dove", fact: "" },
  { name: "Golden-olive Woodpecker", fact: "" },
  { name: "Purple-crowned Fairywren", fact: "" },
  { name: "Chestnut-eared Finch", fact: "" },
  { name: "Red-capped Robin", fact: "" },
  { name: "Blue-cheeked Bee-eater", fact: "" },
  { name: "White-browed Coucal", fact: "" },
  { name: "Yellow-crowned Night Heron", fact: "" },
  { name: "Buff-spotted Flufftail", fact: "" },
  { name: "Grey-headed Albatross", fact: "" },
  { name: "Brown-hooded Kingfisher", fact: "" },
  { name: "White-backed Night Heron", fact: "" },
  { name: "Black-chested Snake Eagle", fact: "" },
  { name: "Rufous-naped Lark", fact: "" },
  { name: "White-eared Barbet", fact: "" },
  { name: "Golden-headed Cisticola", fact: "" },
  { name: "Red-fronted Parrot", fact: "" },
  { name: "Black-faced Antbird", fact: "" },
  { name: "Blue-billed Malimbe", fact: "" },
  { name: "Chestnut-capped Blackbird", fact: "" },
  { name: "Yellow-whiskered Greenbul", fact: "" },
  { name: "White-backed Mousebird", fact: "" },
  { name: "Grey-backed Fiscal", fact: "" },
  { name: "Brown-backed Woodpecker", fact: "" },
  { name: "Blue-crowned Hanging Parrot", fact: "" },
  { name: "Pale-headed Rosella", fact: "" },
  { name: "Red-legged Thrush", fact: "" },
  { name: "Chestnut-flanked White-eye", fact: "" },
  { name: "Golden-cheeked Warbler", fact: "" },
  { name: "Blue-throated Macaw", fact: "" },
  { name: "White-necked Puffbird", fact: "" },
  { name: "Purple-rumped Sunbird", fact: "" },
  { name: "White-bearded Manakin", fact: "" },
  { name: "Crimson-backed Flameback", fact: "" },
  { name: "Blue-backed Tanager", fact: "" },
  { name: "Black-and-yellow Broadbill", fact: "" },
  { name: "Rusty-faced Parrot", fact: "" },
  { name: "White-tailed Nuthatch", fact: "" },
  { name: "Chestnut-headed Bee-eater", fact: "" },
  { name: "Yellow-billed Stork", fact: "" },
  { name: "Red-headed Weaver", fact: "" },
  { name: "Blue-mantled Thornbill", fact: "" },
  { name: "Grey-capped Warbler", fact: "" },
  { name: "Buff-banded Rail", fact: "" },
  { name: "White-rumped Shama", fact: "" },
  { name: "Rufous-backed Robin", fact: "" },
  { name: "Golden-winged Warbler", fact: "" },
  { name: "Purple-naped Lory", fact: "" },
  { name: "Black-capped Donacobius", fact: "" },
  { name: "Orange-backed Woodpecker", fact: "" },
  { name: "White-crested Hornbill", fact: "" },
  { name: "Blue-headed Racket-tail", fact: "" },
  { name: "Red-billed Firefinch", fact: "" },
  { name: "Yellow-eared Bulbul", fact: "" },
  { name: "Grey-necked Wood Rail", fact: "" },
  { name: "Tawny-browed Owl", fact: "" },
  { name: "Chestnut-breasted Wheatear", fact: "" },
  { name: "White-lored Oriole", fact: "" },
  { name: "Brown-winged Starling", fact: "" },
  { name: "Rufous-sided Crake", fact: "" },
  { name: "Golden-tailed Parrotlet", fact: "" },
  { name: "Grey-hooded Attila", fact: "" },
  { name: "Dusky-billed Parrotlet", fact: "" },
  { name: "Black-banded Crake", fact: "" },
  { name: "Tawny-chested Flycatcher", fact: "" },
  { name: "Cinnamon-rumped Foliage-gleaner", fact: "" },
  { name: "White-shouldered Fire-eye", fact: "" },
  { name: "Dusky-throated Antshrike", fact: "" },
  { name: "Brown-chested Jungle Flycatcher", fact: "" },
  { name: "Rufous-throated Bronze Cuckoo", fact: "" },
  { name: "Tawny-winged Woodcreeper", fact: "" },
  { name: "White-browed Tit-warbler", fact: "" },
  { name: "Rufous-capped Nunlet", fact: "" },
  { name: "Black-tipped Cotinga", fact: "" },
  { name: "Yellow-green Vireo", fact: "" },
  { name: "Chestnut-crowned Antpitta", fact: "" },
  { name: "White-ringed Flycatcher", fact: "" },
  { name: "Buff-rumped Warbler", fact: "" },
  { name: "Red-masked Parakeet", fact: "" },
  { name: "Blue-and-yellow Tanager", fact: "" },
  { name: "Grey-mantled Wren", fact: "" },
  { name: "Orange-crowned Euphonia", fact: "" },
  { name: "Black-eared Cuckoo", fact: "" },
  { name: "Rufous-bellied Seedsnipe", fact: "" },
  { name: "White-chinned Petrel", fact: "" },
  { name: "Chestnut-collared Longspur", fact: "" },
  { name: "Yellow-crowned Amazon", fact: "" },
  { name: "Brown-capped Vireo", fact: "" },
  { name: "Tawny-crowned Pygmy Tyrant", fact: "" },
  { name: "Pale-vented Pigeon", fact: "" },
  { name: "Red-throated Pipit", fact: "" },
  { name: "Grey-and-buff Woodpecker", fact: "" },
  { name: "White-naped Tit", fact: "" },
  { name: "Rufous-winged Sparrow", fact: "" },
  { name: "Black-browed Albatross", fact: "" },
  { name: "Golden-breasted Starling", fact: "" },
  { name: "Chestnut-mandibled Toucan", fact: "" },
  { name: "Blue-rumped Parrot", fact: "" },
  { name: "White-bellied Woodstar", fact: "" },
  { name: "Tawny-tufted Toucanet", fact: "" },
  { name: "Red-and-green Macaw", fact: "" },
  { name: "Buff-necked Ibis", fact: "" },
  { name: "Yellow-billed Cotinga", fact: "" },
  { name: "Grey-rumped Swiftlet", fact: "" },
  { name: "White-shouldered Ibis", fact: "" },
  { name: "Rufous-fronted Thornbird", fact: "" },
  { name: "Chestnut-winged Cuckoo", fact: "" },
  { name: "Blue-crowned Trogon", fact: "" },
  { name: "Black-spotted Barbet", fact: "" },
  { name: "White-whiskered Puffbird", fact: "" },
  { name: "Yellow-tufted Woodpecker", fact: "" },
  { name: "Grey-chinned Minivet", fact: "" },
  { name: "Rufous-tailed Scrub Robin", fact: "" },
  { name: "Brown-flanked Bush Warbler", fact: "" },
  { name: "Pale-crowned Cisticola", fact: "" },
  { name: "Black-throated Wattle-eye", fact: "" },
  { name: "Red-winged Pytilia", fact: "" },
  { name: "White-spotted Flufftail", fact: "" },
  { name: "Chestnut-backed Buttonquail", fact: "" },
  { name: "Golden-spectacled Warbler", fact: "" },
  { name: "Black-capped Social Weaver", fact: "" },
  { name: "Yellow-mantled Widowbird", fact: "" },
  { name: "Olive-headed Weaver", fact: "" },
  { name: "Purple-banded Sunbird", fact: "" },
  { name: "White-fronted Scops Owl", fact: "" },
  { name: "Buff-crested Bustard", fact: "" },
  { name: "Brown-headed Paradise Kingfisher", fact: "" },
  { name: "Rufous-bellied Kookaburra", fact: "" },
  { name: "Chestnut-breasted Cuckoo", fact: "" },
  { name: "Black-sided Flowerpecker", fact: "" },
  { name: "White-bellied Erpornis", fact: "" },
  { name: "Golden-fronted Leafbird", fact: "" },
  { name: "Tawny-breasted Honeyeater", fact: "" },
  { name: "Blue-faced Parrotfinch", fact: "" },
  { name: "Scarlet-backed Flowerpecker", fact: "" },
  { name: "Grey-headed Canary-Flycatcher", fact: "" },
  { name: "Red-capped Flowerpecker", fact: "" },
  { name: "Brown-throated Sunbird", fact: "" },
  { name: "Black-headed Bulbul", fact: "" },
  { name: "Crimson-winged Woodpecker", fact: "" },
  { name: "White-bellied Minivet", fact: "" },
  { name: "Orange-bellied Flowerpecker", fact: "" },
  { name: "Black-and-crimson Oriole", fact: "" },
  { name: "Rufous-winged Philentoma", fact: "" },
  { name: "Blue-winged Leafbird", fact: "" },
  { name: "Cream-vented Bulbul", fact: "" },
  { name: "Grey-hooded Broadbill", fact: "" },
  { name: "Dusky Broadbill", fact: "" },
  { name: "Green Broadbill", fact: "" },
  { name: "Silver-breasted Broadbill", fact: "" },
  { name: "Red-throated Barbet", fact: "" },
  { name: "Yellow-crowned Barbet", fact: "" },
  { name: "Golden-whiskered Barbet", fact: "" },
  { name: "Black-browed Barbet", fact: "" },
  { name: "White-chested Babbler", fact: "" },
  { name: "Rufous-tailed Tailorbird", fact: "" },
  { name: "Fluffy-backed Tit-babbler", fact: "" },
  { name: "Chestnut-rumped Babbler", fact: "" },
  { name: "Black-throated Babbler", fact: "" },
  { name: "Ferruginous Babbler", fact: "" },
  { name: "Striped Wren-Babbler", fact: "" },
  { name: "Marbled Wren-Babbler", fact: "" },
  { name: "Short-tailed Babbler", fact: "" },
  { name: "Brown Fulvetta", fact: "" },
  { name: "Mountain Fulvetta", fact: "" },
  { name: "Grey-cheeked Fulvetta", fact: "" },
  { name: "Golden-breasted Fulvetta", fact: "" },
  { name: "Black-browed Reed Warbler", fact: "" },
  { name: "Thick-billed Warbler", fact: "" },
  { name: "Striated Grassbird", fact: "" },
  { name: "Rufous-rumped Grassbird", fact: "" },
  { name: "Marsh Babbler", fact: "" },
  { name: "White-crested Laughingthrush", fact: "" },
  { name: "Chestnut-crowned Laughingthrush", fact: "" },
  { name: "Black-faced Laughingthrush", fact: "" },
  { name: "Scaly Laughingthrush", fact: "" },
  { name: "Streaked Laughingthrush", fact: "" },
  { name: "Blue-winged Laughingthrush", fact: "" },
  { name: "White-gorgeted Flycatcher", fact: "" },
  { name: "Rufous-chested Flycatcher", fact: "" },
  { name: "Verditer Flycatcher", fact: "" },
];
