// ── General bird pool ─────────────────────────────────────────────────────────
// Used for easy / medium modes. Mix of well-known, charismatic, and obscure.
const BIRDS = [

  // Africa
  { name: "Shoebill", fact: "" },
  { name: "Secretary Bird", fact: "" },
  { name: "Hammerkop", fact: "" },
  { name: "Marabou Stork", fact: "" },
  { name: "African Fish Eagle", fact: "" },
  { name: "Lilac-breasted Roller", fact: "" },
  { name: "Southern Ground Hornbill", fact: "" },
  { name: "Hoopoe", fact: "" },
  { name: "Cape Sugarbird", fact: "" },
  { name: "Ostrich", fact: "" },
  { name: "Saddle-billed Stork", fact: "" },
  { name: "African Skimmer", fact: "" },
  { name: "Pel's Fishing Owl", fact: "" },
  { name: "Hartlaub's Turaco", fact: "" },
  { name: "Superb Starling", fact: "" },
  { name: "Kori Bustard", fact: "" },
  { name: "Grey Crowned Crane", fact: "" },
  { name: "Rosy-faced Lovebird", fact: "" },
  { name: "Black-and-white Casqued Hornbill", fact: "" },
  { name: "African Pitta", fact: "" },
  { name: "Martial Eagle", fact: "" },
  { name: "Bateleur", fact: "" },
  { name: "Namaqua Sandgrouse", fact: "" },
  { name: "Long-crested Eagle", fact: "" },
  { name: "Pennant-winged Nightjar", fact: "" },
  { name: "Black Heron", fact: "" },
  { name: "Greater Honeyguide", fact: "" },
  { name: "Long-tailed Widowbird", fact: "" },
  { name: "African Broadbill", fact: "" },
  { name: "African Finfoot", fact: "" },
  { name: "Sunbird Asity", fact: "" },
  { name: "Lappet-faced Vulture", fact: "" },
  { name: "Hooded Vulture", fact: "" },
  { name: "Verreaux's Eagle", fact: "" },
  { name: "Taita Falcon", fact: "" },
  { name: "White-fronted Bee-eater", fact: "" },
  { name: "African Jacana", fact: "" },
  { name: "Knysna Turaco", fact: "" },
  { name: "African Openbill", fact: "" },
  { name: "Palm-nut Vulture", fact: "" },

  // Asia
  { name: "Indian Peafowl", fact: "" },
  { name: "Himalayan Monal", fact: "" },
  { name: "Red-crowned Crane", fact: "" },
  { name: "Oriental Pied Hornbill", fact: "" },
  { name: "Sarus Crane", fact: "" },
  { name: "Indian Roller", fact: "" },
  { name: "Painted Stork", fact: "" },
  { name: "Indian Paradise Flycatcher", fact: "" },
  { name: "Siberian Crane", fact: "" },
  { name: "Great Hornbill", fact: "" },
  { name: "Brahminy Kite", fact: "" },
  { name: "Sri Lanka Frogmouth", fact: "" },
  { name: "Stork-billed Kingfisher", fact: "" },
  { name: "Blue Pitta", fact: "" },
  { name: "Jerdon's Courser", fact: "" },
  { name: "Malabar Trogon", fact: "" },
  { name: "Spoon-billed Sandpiper", fact: "" },
  { name: "Milky Stork", fact: "" },
  { name: "Bar-headed Goose", fact: "" },
  { name: "Mandarin Duck", fact: "" },
  { name: "Walden's Hornbill", fact: "" },
  { name: "Bornean Bristlehead", fact: "" },
  { name: "Wrinkled Hornbill", fact: "" },
  { name: "Gurney's Pitta", fact: "" },
  { name: "Philippine Eagle", fact: "" },
  { name: "Palawan Peacock-Pheasant", fact: "" },
  { name: "Storm's Stork", fact: "" },
  { name: "Crested Serpent Eagle", fact: "" },
  { name: "Cheer Pheasant", fact: "" },
  { name: "Satyr Tragopan", fact: "" },
  { name: "Temminck's Tragopan", fact: "" },
  { name: "Green Peafowl", fact: "" },
  { name: "Wilson's Bird-of-Paradise", fact: "" },
  { name: "Wallace's Standardwing", fact: "" },
  { name: "Maleo", fact: "" },
  { name: "Nicobar Pigeon", fact: "" },
  { name: "Black-naped Pheasant-Pigeon", fact: "" },
  { name: "Halmahera Paradise Crow", fact: "" },
  { name: "Spot-billed Pelican", fact: "" },
  { name: "Pied Kingfisher", fact: "" },

  // Australasia & New Zealand
  { name: "Cassowary", fact: "" },
  { name: "Kea", fact: "" },
  { name: "Kiwi", fact: "" },
  { name: "Tawny Frogmouth", fact: "" },
  { name: "Superb Lyrebird", fact: "" },
  { name: "Rifleman", fact: "" },
  { name: "Laughing Kookaburra", fact: "" },
  { name: "Kakapo", fact: "" },
  { name: "Satin Bowerbird", fact: "" },
  { name: "Regent Bowerbird", fact: "" },
  { name: "Tooth-billed Bowerbird", fact: "" },
  { name: "Vogelkop Bowerbird", fact: "" },
  { name: "Raggiana Bird-of-Paradise", fact: "" },
  { name: "King Bird-of-Paradise", fact: "" },
  { name: "Western Parotia", fact: "" },
  { name: "King-of-Saxony Bird-of-Paradise", fact: "" },
  { name: "Blue Bird-of-Paradise", fact: "" },
  { name: "Twelve-wired Bird-of-Paradise", fact: "" },
  { name: "Magnificent Riflebird", fact: "" },
  { name: "Victoria Crowned Pigeon", fact: "" },
  { name: "Palm Cockatoo", fact: "" },
  { name: "Gang-gang Cockatoo", fact: "" },
  { name: "Glossy Black-Cockatoo", fact: "" },
  { name: "Yellow-tailed Black-Cockatoo", fact: "" },
  { name: "Swift Parrot", fact: "" },
  { name: "Orange-bellied Parrot", fact: "" },
  { name: "Pesquet's Parrot", fact: "" },
  { name: "Eclectus Parrot", fact: "" },
  { name: "Emu", fact: "" },
  { name: "Wedge-tailed Eagle", fact: "" },
  { name: "Australian Brushturkey", fact: "" },
  { name: "Malleefowl", fact: "" },
  { name: "Plains-wanderer", fact: "" },
  { name: "Night Parrot", fact: "" },
  { name: "Gouldian Finch", fact: "" },
  { name: "Splendid Fairywren", fact: "" },
  { name: "Noisy Scrubbird", fact: "" },
  { name: "Powerful Owl", fact: "" },
  { name: "Apostlebird", fact: "" },
  { name: "Chowchilla", fact: "" },
  { name: "Takahe", fact: "" },
  { name: "Wrybill", fact: "" },
  { name: "Black Stilt", fact: "" },
  { name: "New Zealand Bellbird", fact: "" },
  { name: "Hihi", fact: "" },
  { name: "Kokako", fact: "" },
  { name: "Saddleback", fact: "" },
  { name: "Kaka", fact: "" },
  { name: "Weka", fact: "" },
  { name: "New Zealand Dotterel", fact: "" },
  { name: "Logrunner", fact: "" },

  // Europe
  { name: "Bearded Vulture", fact: "" },
  { name: "European Bee-eater", fact: "" },
  { name: "Common Kingfisher", fact: "" },
  { name: "Atlantic Puffin", fact: "" },
  { name: "Great Bustard", fact: "" },
  { name: "White-tailed Eagle", fact: "" },
  { name: "Eurasian Bittern", fact: "" },
  { name: "Dalmatian Pelican", fact: "" },
  { name: "Eurasian Eagle Owl", fact: "" },
  { name: "Great Grey Shrike", fact: "" },
  { name: "Wallcreeper", fact: "" },
  { name: "Snow Bunting", fact: "" },
  { name: "Eurasian Dotterel", fact: "" },
  { name: "Ruff", fact: "" },
  { name: "Red Kite", fact: "" },
  { name: "Eurasian Roller", fact: "" },
  { name: "Wryneck", fact: "" },
  { name: "Eurasian Spoonbill", fact: "" },
  { name: "Black Woodpecker", fact: "" },
  { name: "Hawfinch", fact: "" },
  { name: "Penduline Tit", fact: "" },
  { name: "White-winged Snowfinch", fact: "" },
  { name: "Cinereous Vulture", fact: "" },
  { name: "Common Firecrest", fact: "" },
  { name: "Bluethroat", fact: "" },
  { name: "Pygmy Cormorant", fact: "" },
  { name: "Eurasian Scops Owl", fact: "" },
  { name: "Tengmalm's Owl", fact: "" },
  { name: "Great Snipe", fact: "" },
  { name: "Eurasian Woodcock", fact: "" },

  // North America
  { name: "Arctic Tern", fact: "" },
  { name: "Peregrine Falcon", fact: "" },
  { name: "Snowy Owl", fact: "" },
  { name: "Greater Roadrunner", fact: "" },
  { name: "Clark's Nutcracker", fact: "" },
  { name: "Burrowing Owl", fact: "" },
  { name: "Common Loon", fact: "" },
  { name: "Osprey", fact: "" },
  { name: "Anna's Hummingbird", fact: "" },
  { name: "Bobolink", fact: "" },
  { name: "Red Knot", fact: "" },
  { name: "Limpkin", fact: "" },
  { name: "Snail Kite", fact: "" },
  { name: "American Dipper", fact: "" },
  { name: "Harlequin Duck", fact: "" },
  { name: "Painted Bunting", fact: "" },
  { name: "Scissor-tailed Flycatcher", fact: "" },
  { name: "Long-billed Curlew", fact: "" },
  { name: "Whooping Crane", fact: "" },
  { name: "California Condor", fact: "" },
  { name: "Vermilion Flycatcher", fact: "" },
  { name: "Phainopepla", fact: "" },
  { name: "Elf Owl", fact: "" },
  { name: "Elegant Trogon", fact: "" },
  { name: "Thick-billed Parrot", fact: "" },
  { name: "Marbled Murrelet", fact: "" },
  { name: "Western Grebe", fact: "" },
  { name: "Spruce Grouse", fact: "" },
  { name: "Tufted Puffin", fact: "" },
  { name: "Rhinoceros Auklet", fact: "" },
  { name: "Ivory Gull", fact: "" },
  { name: "Ross's Gull", fact: "" },
  { name: "Steller's Sea Eagle", fact: "" },
  { name: "Bristle-thighed Curlew", fact: "" },
  { name: "Kirtland's Warbler", fact: "" },
  { name: "Prothonotary Warbler", fact: "" },
  { name: "Gunnison Sage-Grouse", fact: "" },
  { name: "Roseate Spoonbill", fact: "" },

  // Central America & Caribbean
  { name: "Resplendent Quetzal", fact: "" },
  { name: "Turquoise-browed Motmot", fact: "" },
  { name: "Keel-billed Toucan", fact: "" },
  { name: "Harpy Eagle", fact: "" },
  { name: "Sunbittern", fact: "" },
  { name: "Bee Hummingbird", fact: "" },
  { name: "Wire-tailed Manakin", fact: "" },
  { name: "Club-winged Manakin", fact: "" },
  { name: "Amazonian Umbrellabird", fact: "" },
  { name: "Spectacled Owl", fact: "" },
  { name: "Sungrebe", fact: "" },
  { name: "Agami Heron", fact: "" },
  { name: "Zigzag Heron", fact: "" },
  { name: "Snowcap", fact: "" },
  { name: "Royal Flycatcher", fact: "" },
  { name: "Purple-crowned Fairy", fact: "" },
  { name: "Fiery-throated Hummingbird", fact: "" },
  { name: "Great Curassow", fact: "" },
  { name: "Lovely Cotinga", fact: "" },
  { name: "Snowy Cotinga", fact: "" },

  // South America
  { name: "Andean Condor", fact: "" },
  { name: "Hoatzin", fact: "" },
  { name: "Cock-of-the-rock", fact: "" },
  { name: "Horned Screamer", fact: "" },
  { name: "Jabiru", fact: "" },
  { name: "Inca Tern", fact: "" },
  { name: "Emperor Penguin", fact: "" },
  { name: "Rockhopper Penguin", fact: "" },
  { name: "Macaroni Penguin", fact: "" },
  { name: "Magellanic Penguin", fact: "" },
  { name: "Torrent Duck", fact: "" },
  { name: "Oilbird", fact: "" },
  { name: "Capuchinbird", fact: "" },
  { name: "Purple-breasted Cotinga", fact: "" },
  { name: "Banded Cotinga", fact: "" },
  { name: "Long-wattled Umbrellabird", fact: "" },
  { name: "Common Potoo", fact: "" },
  { name: "Great Potoo", fact: "" },
  { name: "Pale-winged Trumpeter", fact: "" },
  { name: "Giant Antpitta", fact: "" },
  { name: "Coppery-chested Jacamar", fact: "" },
  { name: "Rufescent Tiger Heron", fact: "" },
  { name: "Titicaca Grebe", fact: "" },
  { name: "James's Flamingo", fact: "" },
  { name: "Puna Flamingo", fact: "" },
  { name: "Hooded Grebe", fact: "" },
  { name: "Giant Coot", fact: "" },
  { name: "Wattled Curassow", fact: "" },
  { name: "Maguari Stork", fact: "" },
  { name: "Toco Toucan", fact: "" },

  // Seabirds & Polar
  { name: "Wandering Albatross", fact: "" },
  { name: "Waved Albatross", fact: "" },
  { name: "Light-mantled Albatross", fact: "" },
  { name: "Southern Giant Petrel", fact: "" },
  { name: "Snow Petrel", fact: "" },
  { name: "Blue-footed Booby", fact: "" },
  { name: "Red-footed Booby", fact: "" },
  { name: "Magnificent Frigatebird", fact: "" },
  { name: "White Tern", fact: "" },
  { name: "South Polar Skua", fact: "" },
  { name: "Long-tailed Jaeger", fact: "" },
  { name: "Swallow-tailed Gull", fact: "" },
  { name: "Sooty Shearwater", fact: "" },
  { name: "Manx Shearwater", fact: "" },
  { name: "Wilson's Storm Petrel", fact: "" },
  { name: "Red-billed Tropicbird", fact: "" },
  { name: "White-tailed Tropicbird", fact: "" },
  { name: "Abbott's Booby", fact: "" },
  { name: "Masked Booby", fact: "" },
  { name: "Brown Noddy", fact: "" },
  { name: "Christmas Frigatebird", fact: "" },

  // Owls & Nightbirds
  { name: "Great Grey Owl", fact: "" },
  { name: "Blakiston's Fish Owl", fact: "" },
  { name: "Verreaux's Eagle Owl", fact: "" },
  { name: "Crested Owl", fact: "" },
  { name: "Long-eared Owl", fact: "" },
  { name: "Barn Owl", fact: "" },
  { name: "Papuan Frogmouth", fact: "" },
  { name: "Standard-winged Nightjar", fact: "" },
  { name: "Lyre-tailed Nightjar", fact: "" },
  { name: "Pharaoh Eagle Owl", fact: "" },

];

// ── Hard-mode bird pool ───────────────────────────────────────────────────────
// Compound hyphenated names that match the SNEAKY fake-name generator style.
const HARD_BIRDS = [
  { name: "Yellow-rumped Warbler", fact: "" },
  { name: "Black-crowned Night Heron", fact: "" },
  { name: "Red-tailed Hawk", fact: "" },
  { name: "White-throated Sparrow", fact: "" },
  { name: "Blue-winged Teal", fact: "" },
  { name: "Golden-fronted Woodpecker", fact: "" },
  { name: "Red-breasted Nuthatch", fact: "" },
  { name: "Yellow-bellied Sapsucker", fact: "" },
  { name: "Golden-crowned Kinglet", fact: "" },
  { name: "Black-bellied Plover", fact: "" },
  { name: "White-crowned Sparrow", fact: "" },
  { name: "Chestnut-backed Chickadee", fact: "" },
  { name: "Rufous-tailed Hummingbird", fact: "" },
  { name: "Black-backed Woodpecker", fact: "" },
  { name: "Olive-backed Sunbird", fact: "" },
  { name: "White-bellied Sea Eagle", fact: "" },
  { name: "Rufous-crowned Sparrow", fact: "" },
  { name: "Yellow-billed Oxpecker", fact: "" },
  { name: "Blue-naped Mousebird", fact: "" },
  { name: "Chestnut-sided Warbler", fact: "" },
  { name: "Red-faced Cormorant", fact: "" },
  { name: "White-winged Crossbill", fact: "" },
  { name: "Black-headed Grosbeak", fact: "" },
  { name: "Yellow-fronted Canary", fact: "" },
  { name: "Rufous-bellied Niltava", fact: "" },
  { name: "Purple-backed Thornbill", fact: "" },
  { name: "Blue-faced Honeyeater", fact: "" },
  { name: "Red-necked Phalarope", fact: "" },
  { name: "White-cheeked Pintail", fact: "" },
  { name: "Tawny-flanked Prinia", fact: "" },
  { name: "Golden-backed Weaver", fact: "" },
  { name: "Black-winged Stilt", fact: "" },
  { name: "Buff-fronted Owl", fact: "" },
  { name: "Yellow-throated Longclaw", fact: "" },
  { name: "White-headed Vulture", fact: "" },
  { name: "Red-chested Swallow", fact: "" },
  { name: "Blue-spotted Wood Dove", fact: "" },
  { name: "Pale-billed Woodpecker", fact: "" },
  { name: "Black-throated Mango", fact: "" },
  { name: "White-tipped Dove", fact: "" },
  { name: "Golden-olive Woodpecker", fact: "" },
  { name: "Purple-crowned Fairywren", fact: "" },
  { name: "Chestnut-eared Finch", fact: "" },
  { name: "Red-capped Robin", fact: "" },
  { name: "Blue-cheeked Bee-eater", fact: "" },
  { name: "White-browed Coucal", fact: "" },
  { name: "Yellow-crowned Night Heron", fact: "" },
  { name: "Buff-spotted Flufftail", fact: "" },
  { name: "Grey-headed Albatross", fact: "" },
  { name: "Brown-hooded Kingfisher", fact: "" },
  { name: "White-backed Night Heron", fact: "" },
  { name: "Black-chested Snake Eagle", fact: "" },
  { name: "Rufous-naped Lark", fact: "" },
  { name: "White-eared Barbet", fact: "" },
  { name: "Golden-headed Cisticola", fact: "" },
  { name: "Red-fronted Parrot", fact: "" },
  { name: "Black-faced Antbird", fact: "" },
  { name: "Blue-billed Malimbe", fact: "" },
  { name: "Chestnut-capped Blackbird", fact: "" },
  { name: "Yellow-whiskered Greenbul", fact: "" },
  { name: "White-backed Mousebird", fact: "" },
  { name: "Grey-backed Fiscal", fact: "" },
  { name: "Brown-backed Woodpecker", fact: "" },
  { name: "Blue-crowned Hanging Parrot", fact: "" },
  { name: "Pale-headed Rosella", fact: "" },
  { name: "Red-legged Thrush", fact: "" },
  { name: "Chestnut-flanked White-eye", fact: "" },
  { name: "Golden-cheeked Warbler", fact: "" },
  { name: "Blue-throated Macaw", fact: "" },
  { name: "White-necked Puffbird", fact: "" },
  { name: "Purple-rumped Sunbird", fact: "" },
  { name: "White-bearded Manakin", fact: "" },
  { name: "Crimson-backed Flameback", fact: "" },
  { name: "Blue-backed Tanager", fact: "" },
  { name: "Black-and-yellow Broadbill", fact: "" },
  { name: "Rusty-faced Parrot", fact: "" },
  { name: "White-tailed Nuthatch", fact: "" },
  { name: "Chestnut-headed Bee-eater", fact: "" },
  { name: "Yellow-billed Stork", fact: "" },
  { name: "Red-headed Weaver", fact: "" },
  { name: "Blue-mantled Thornbill", fact: "" },
  { name: "Grey-capped Warbler", fact: "" },
  { name: "Buff-banded Rail", fact: "" },
  { name: "White-rumped Shama", fact: "" },
  { name: "Rufous-backed Robin", fact: "" },
  { name: "Golden-winged Warbler", fact: "" },
  { name: "Purple-naped Lory", fact: "" },
  { name: "Black-capped Donacobius", fact: "" },
  { name: "Orange-backed Woodpecker", fact: "" },
  { name: "White-crested Hornbill", fact: "" },
  { name: "Blue-headed Racket-tail", fact: "" },
  { name: "Red-billed Firefinch", fact: "" },
  { name: "Yellow-eared Bulbul", fact: "" },
  { name: "Grey-necked Wood Rail", fact: "" },
  { name: "Tawny-browed Owl", fact: "" },
  { name: "Chestnut-breasted Wheatear", fact: "" },
  { name: "White-lored Oriole", fact: "" },
  { name: "Brown-winged Starling", fact: "" },
  { name: "Rufous-sided Crake", fact: "" },
  { name: "Golden-tailed Parrotlet", fact: "" },
  { name: "Grey-hooded Attila", fact: "" },
  { name: "Dusky-billed Parrotlet", fact: "" },
  { name: "Black-banded Crake", fact: "" },
  { name: "Tawny-chested Flycatcher", fact: "" },
  { name: "Cinnamon-rumped Foliage-gleaner", fact: "" },
  { name: "White-shouldered Fire-eye", fact: "" },
  { name: "Dusky-throated Antshrike", fact: "" },
  { name: "Brown-chested Jungle Flycatcher", fact: "" },
  { name: "Rufous-throated Bronze Cuckoo", fact: "" },
  { name: "Tawny-winged Woodcreeper", fact: "" },
  { name: "White-browed Tit-warbler", fact: "" },
  { name: "Rufous-capped Nunlet", fact: "" },
  { name: "Black-tipped Cotinga", fact: "" },
  { name: "Yellow-green Vireo", fact: "" },
  { name: "Chestnut-crowned Antpitta", fact: "" },
  { name: "White-ringed Flycatcher", fact: "" },
  { name: "Buff-rumped Warbler", fact: "" },
  { name: "Red-masked Parakeet", fact: "" },
  { name: "Blue-and-yellow Tanager", fact: "" },
  { name: "Grey-mantled Wren", fact: "" },
  { name: "Orange-crowned Euphonia", fact: "" },
  { name: "Black-eared Cuckoo", fact: "" },
  { name: "Rufous-bellied Seedsnipe", fact: "" },
  { name: "White-chinned Petrel", fact: "" },
  { name: "Chestnut-collared Longspur", fact: "" },
  { name: "Yellow-crowned Amazon", fact: "" },
  { name: "Brown-capped Vireo", fact: "" },
  { name: "Tawny-crowned Pygmy Tyrant", fact: "" },
  { name: "Pale-vented Pigeon", fact: "" },
  { name: "Red-throated Pipit", fact: "" },
  { name: "Grey-and-buff Woodpecker", fact: "" },
  { name: "White-naped Tit", fact: "" },
  { name: "Rufous-winged Sparrow", fact: "" },
  { name: "Black-browed Albatross", fact: "" },
  { name: "Golden-breasted Starling", fact: "" },
  { name: "Chestnut-mandibled Toucan", fact: "" },
  { name: "Blue-rumped Parrot", fact: "" },
  { name: "White-bellied Woodstar", fact: "" },
  { name: "Tawny-tufted Toucanet", fact: "" },
  { name: "Red-and-green Macaw", fact: "" },
  { name: "Buff-necked Ibis", fact: "" },
  { name: "Yellow-billed Cotinga", fact: "" },
  { name: "Grey-rumped Swiftlet", fact: "" },
  { name: "White-shouldered Ibis", fact: "" },
  { name: "Rufous-fronted Thornbird", fact: "" },
  { name: "Chestnut-winged Cuckoo", fact: "" },
  { name: "Blue-crowned Trogon", fact: "" },
  { name: "Black-spotted Barbet", fact: "" },
  { name: "White-whiskered Puffbird", fact: "" },
  { name: "Yellow-tufted Woodpecker", fact: "" },
  { name: "Grey-chinned Minivet", fact: "" },
  { name: "Rufous-tailed Scrub Robin", fact: "" },
  { name: "Brown-flanked Bush Warbler", fact: "" },
  { name: "Pale-crowned Cisticola", fact: "" },
  { name: "Black-throated Wattle-eye", fact: "" },
  { name: "Red-winged Pytilia", fact: "" },
  { name: "White-spotted Flufftail", fact: "" },
  { name: "Chestnut-backed Buttonquail", fact: "" },
  { name: "Golden-spectacled Warbler", fact: "" },
  { name: "Black-capped Social Weaver", fact: "" },
  { name: "Yellow-mantled Widowbird", fact: "" },
  { name: "Olive-headed Weaver", fact: "" },
  { name: "Purple-banded Sunbird", fact: "" },
  { name: "White-fronted Scops Owl", fact: "" },
  { name: "Buff-crested Bustard", fact: "" },
  { name: "Brown-headed Paradise Kingfisher", fact: "" },
  { name: "Rufous-bellied Kookaburra", fact: "" },
  { name: "Chestnut-breasted Cuckoo", fact: "" },
  { name: "Black-sided Flowerpecker", fact: "" },
  { name: "White-bellied Erpornis", fact: "" },
  { name: "Golden-fronted Leafbird", fact: "" },
  { name: "Tawny-breasted Honeyeater", fact: "" },
  { name: "Blue-faced Parrotfinch", fact: "" },
  { name: "Scarlet-backed Flowerpecker", fact: "" },
  { name: "Grey-headed Canary-Flycatcher", fact: "" },
  { name: "Red-capped Flowerpecker", fact: "" },
  { name: "Brown-throated Sunbird", fact: "" },
  { name: "Black-headed Bulbul", fact: "" },
  { name: "Crimson-winged Woodpecker", fact: "" },
  { name: "White-bellied Minivet", fact: "" },
  { name: "Orange-bellied Flowerpecker", fact: "" },
  { name: "Black-and-crimson Oriole", fact: "" },
  { name: "Rufous-winged Philentoma", fact: "" },
  { name: "Blue-winged Leafbird", fact: "" },
  { name: "Cream-vented Bulbul", fact: "" },
  { name: "Grey-hooded Broadbill", fact: "" },
  { name: "Dusky Broadbill", fact: "" },
  { name: "Green Broadbill", fact: "" },
  { name: "Silver-breasted Broadbill", fact: "" },
  { name: "Red-throated Barbet", fact: "" },
  { name: "Yellow-crowned Barbet", fact: "" },
  { name: "Golden-whiskered Barbet", fact: "" },
  { name: "Black-browed Barbet", fact: "" },
  { name: "White-chested Babbler", fact: "" },
  { name: "Rufous-tailed Tailorbird", fact: "" },
  { name: "Fluffy-backed Tit-babbler", fact: "" },
  { name: "Chestnut-rumped Babbler", fact: "" },
  { name: "Black-throated Babbler", fact: "" },
  { name: "Ferruginous Babbler", fact: "" },
  { name: "Striped Wren-Babbler", fact: "" },
  { name: "Marbled Wren-Babbler", fact: "" },
  { name: "Short-tailed Babbler", fact: "" },
  { name: "Brown Fulvetta", fact: "" },
  { name: "Mountain Fulvetta", fact: "" },
  { name: "Grey-cheeked Fulvetta", fact: "" },
  { name: "Golden-breasted Fulvetta", fact: "" },
  { name: "Black-browed Reed Warbler", fact: "" },
  { name: "Thick-billed Warbler", fact: "" },
  { name: "Striated Grassbird", fact: "" },
  { name: "Rufous-rumped Grassbird", fact: "" },
  { name: "Marsh Babbler", fact: "" },
  { name: "White-crested Laughingthrush", fact: "" },
  { name: "Chestnut-crowned Laughingthrush", fact: "" },
  { name: "Black-faced Laughingthrush", fact: "" },
  { name: "Scaly Laughingthrush", fact: "" },
  { name: "Streaked Laughingthrush", fact: "" },
  { name: "Blue-winged Laughingthrush", fact: "" },
  { name: "White-gorgeted Flycatcher", fact: "" },
  { name: "Rufous-chested Flycatcher", fact: "" },
  { name: "Verditer Flycatcher", fact: "" },
];
